<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:nlb="http://www.nlb.no/"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                exclude-result-prefixes="#all"
                version="2.0">
    
    <xsl:function name="nlb:role-to-marcrel" as="xs:string">
        <xsl:param name="marcrel" as="xs:string"/>
        <xsl:choose>
            <xsl:when test="$marcrel = 'abridger'"><xsl:value-of select="'abr'"/></xsl:when>
            <xsl:when test="$marcrel = 'actor'"><xsl:value-of select="'act'"/></xsl:when>
            <xsl:when test="$marcrel = 'adapter'"><xsl:value-of select="'adp'"/></xsl:when>
            <xsl:when test="$marcrel = 'analyst'"><xsl:value-of select="'anl'"/></xsl:when>
            <xsl:when test="$marcrel = 'animator'"><xsl:value-of select="'anm'"/></xsl:when>
            <xsl:when test="$marcrel = 'annotator'"><xsl:value-of select="'ann'"/></xsl:when>
            <xsl:when test="$marcrel = 'appellee'"><xsl:value-of select="'ape'"/></xsl:when>
            <xsl:when test="$marcrel = 'appellant'"><xsl:value-of select="'apl'"/></xsl:when>
            <xsl:when test="$marcrel = 'applicant'"><xsl:value-of select="'app'"/></xsl:when>
            <xsl:when test="$marcrel = 'architect'"><xsl:value-of select="'arc'"/></xsl:when>
            <xsl:when test="$marcrel = 'arranger'"><xsl:value-of select="'arr'"/></xsl:when>
            <xsl:when test="$marcrel = 'artist'"><xsl:value-of select="'art'"/></xsl:when>
            <xsl:when test="$marcrel = 'assignee'"><xsl:value-of select="'asg'"/></xsl:when>
            <xsl:when test="$marcrel = 'autographer'"><xsl:value-of select="'ato'"/></xsl:when>
            <xsl:when test="$marcrel = 'auctioneer'"><xsl:value-of select="'auc'"/></xsl:when>
            <xsl:when test="$marcrel = 'screenwriter'"><xsl:value-of select="'aus'"/></xsl:when>
            <xsl:when test="$marcrel = 'author'"><xsl:value-of select="'aut'"/></xsl:when>
            <xsl:when test="$marcrel = 'binder'"><xsl:value-of select="'bnd'"/></xsl:when>
            <xsl:when test="$marcrel = 'broadcaster'"><xsl:value-of select="'brd'"/></xsl:when>
            <xsl:when test="$marcrel = 'bookseller'"><xsl:value-of select="'bsl'"/></xsl:when>
            <xsl:when test="$marcrel = 'caster'"><xsl:value-of select="'cas'"/></xsl:when>
            <xsl:when test="$marcrel = 'conceptor'"><xsl:value-of select="'ccp'"/></xsl:when>
            <xsl:when test="$marcrel = 'choreographer'"><xsl:value-of select="'chr'"/></xsl:when>
            <xsl:when test="$marcrel = 'client'"><xsl:value-of select="'cli'"/></xsl:when>
            <xsl:when test="$marcrel = 'calligrapher'"><xsl:value-of select="'cll'"/></xsl:when>
            <xsl:when test="$marcrel = 'colorist'"><xsl:value-of select="'clr'"/></xsl:when>
            <xsl:when test="$marcrel = 'collotyper'"><xsl:value-of select="'clt'"/></xsl:when>
            <xsl:when test="$marcrel = 'commentator'"><xsl:value-of select="'cmm'"/></xsl:when>
            <xsl:when test="$marcrel = 'composer'"><xsl:value-of select="'cmp'"/></xsl:when>
            <xsl:when test="$marcrel = 'compositor'"><xsl:value-of select="'cmt'"/></xsl:when>
            <xsl:when test="$marcrel = 'conductor'"><xsl:value-of select="'cnd'"/></xsl:when>
            <xsl:when test="$marcrel = 'cinematographer'"><xsl:value-of select="'cng'"/></xsl:when>
            <xsl:when test="$marcrel = 'censor'"><xsl:value-of select="'cns'"/></xsl:when>
            <xsl:when test="$marcrel = 'contestant-appellee'"><xsl:value-of select="'coe'"/></xsl:when>
            <xsl:when test="$marcrel = 'collector'"><xsl:value-of select="'col'"/></xsl:when>
            <xsl:when test="$marcrel = 'compiler'"><xsl:value-of select="'com'"/></xsl:when>
            <xsl:when test="$marcrel = 'conservator'"><xsl:value-of select="'con'"/></xsl:when>
            <xsl:when test="$marcrel = 'contestant'"><xsl:value-of select="'cos'"/></xsl:when>
            <xsl:when test="$marcrel = 'contestant-appellant'"><xsl:value-of select="'cot'"/></xsl:when>
            <xsl:when test="$marcrel = 'complainant-appellee'"><xsl:value-of select="'cpe'"/></xsl:when>
            <xsl:when test="$marcrel = 'complainant'"><xsl:value-of select="'cpl'"/></xsl:when>
            <xsl:when test="$marcrel = 'complainant-appellant'"><xsl:value-of select="'cpt'"/></xsl:when>
            <xsl:when test="$marcrel = 'creator'"><xsl:value-of select="'cre'"/></xsl:when>
            <xsl:when test="$marcrel = 'correspondent'"><xsl:value-of select="'crp'"/></xsl:when>
            <xsl:when test="$marcrel = 'corrector'"><xsl:value-of select="'crr'"/></xsl:when>
            <xsl:when test="$marcrel = 'consultant'"><xsl:value-of select="'csl'"/></xsl:when>
            <xsl:when test="$marcrel = 'contributor'"><xsl:value-of select="'ctb'"/></xsl:when>
            <xsl:when test="$marcrel = 'contestee-appellee'"><xsl:value-of select="'cte'"/></xsl:when>
            <xsl:when test="$marcrel = 'cartographer'"><xsl:value-of select="'ctg'"/></xsl:when>
            <xsl:when test="$marcrel = 'contractor'"><xsl:value-of select="'ctr'"/></xsl:when>
            <xsl:when test="$marcrel = 'contestee'"><xsl:value-of select="'cts'"/></xsl:when>
            <xsl:when test="$marcrel = 'contestee-appellant'"><xsl:value-of select="'ctt'"/></xsl:when>
            <xsl:when test="$marcrel = 'curator'"><xsl:value-of select="'cur'"/></xsl:when>
            <xsl:when test="$marcrel = 'defendant'"><xsl:value-of select="'dfd'"/></xsl:when>
            <xsl:when test="$marcrel = 'defendant-appellee'"><xsl:value-of select="'dfe'"/></xsl:when>
            <xsl:when test="$marcrel = 'defendant-appellant'"><xsl:value-of select="'dft'"/></xsl:when>
            <xsl:when test="$marcrel = 'dissertant'"><xsl:value-of select="'dis'"/></xsl:when>
            <xsl:when test="$marcrel = 'delineator'"><xsl:value-of select="'dln'"/></xsl:when>
            <xsl:when test="$marcrel = 'dancer'"><xsl:value-of select="'dnc'"/></xsl:when>
            <xsl:when test="$marcrel = 'donor'"><xsl:value-of select="'dnr'"/></xsl:when>
            <xsl:when test="$marcrel = 'depicted'"><xsl:value-of select="'dpc'"/></xsl:when>
            <xsl:when test="$marcrel = 'depositor'"><xsl:value-of select="'dpt'"/></xsl:when>
            <xsl:when test="$marcrel = 'draftsman'"><xsl:value-of select="'drm'"/></xsl:when>
            <xsl:when test="$marcrel = 'director'"><xsl:value-of select="'drt'"/></xsl:when>
            <xsl:when test="$marcrel = 'designer'"><xsl:value-of select="'dsr'"/></xsl:when>
            <xsl:when test="$marcrel = 'distributor'"><xsl:value-of select="'dst'"/></xsl:when>
            <xsl:when test="$marcrel = 'dedicatee'"><xsl:value-of select="'dte'"/></xsl:when>
            <xsl:when test="$marcrel = 'dedicator'"><xsl:value-of select="'dto'"/></xsl:when>
            <xsl:when test="$marcrel = 'editor'"><xsl:value-of select="'edt'"/></xsl:when>
            <xsl:when test="$marcrel = 'engraver'"><xsl:value-of select="'egr'"/></xsl:when>
            <xsl:when test="$marcrel = 'electrician'"><xsl:value-of select="'elg'"/></xsl:when>
            <xsl:when test="$marcrel = 'electrotyper'"><xsl:value-of select="'elt'"/></xsl:when>
            <xsl:when test="$marcrel = 'engineer'"><xsl:value-of select="'eng'"/></xsl:when>
            <xsl:when test="$marcrel = 'etcher'"><xsl:value-of select="'etr'"/></xsl:when>
            <xsl:when test="$marcrel = 'expert'"><xsl:value-of select="'exp'"/></xsl:when>
            <xsl:when test="$marcrel = 'facsimilist'"><xsl:value-of select="'fac'"/></xsl:when>
            <xsl:when test="$marcrel = 'filmmaker'"><xsl:value-of select="'fmk'"/></xsl:when>
            <xsl:when test="$marcrel = 'funder'"><xsl:value-of select="'fnd'"/></xsl:when>
            <xsl:when test="$marcrel = 'forger'"><xsl:value-of select="'frg'"/></xsl:when>
            <xsl:when test="$marcrel = 'honoree'"><xsl:value-of select="'hnr'"/></xsl:when>
            <xsl:when test="$marcrel = 'host'"><xsl:value-of select="'hst'"/></xsl:when>
            <xsl:when test="$marcrel = 'illustrator'"><xsl:value-of select="'ill'"/></xsl:when>
            <xsl:when test="$marcrel = 'illuminator'"><xsl:value-of select="'ilu'"/></xsl:when>
            <xsl:when test="$marcrel = 'inscriber'"><xsl:value-of select="'ins'"/></xsl:when>
            <xsl:when test="$marcrel = 'inventor'"><xsl:value-of select="'inv'"/></xsl:when>
            <xsl:when test="$marcrel = 'instrumentalist'"><xsl:value-of select="'itr'"/></xsl:when>
            <xsl:when test="$marcrel = 'interviewee'"><xsl:value-of select="'ive'"/></xsl:when>
            <xsl:when test="$marcrel = 'interviewer'"><xsl:value-of select="'ivr'"/></xsl:when>
            <xsl:when test="$marcrel = 'judge'"><xsl:value-of select="'jud'"/></xsl:when>
            <xsl:when test="$marcrel = 'laboratory'"><xsl:value-of select="'lbr'"/></xsl:when>
            <xsl:when test="$marcrel = 'librettist'"><xsl:value-of select="'lbt'"/></xsl:when>
            <xsl:when test="$marcrel = 'lead'"><xsl:value-of select="'led'"/></xsl:when>
            <xsl:when test="$marcrel = 'libelee-appellee'"><xsl:value-of select="'lee'"/></xsl:when>
            <xsl:when test="$marcrel = 'libelee'"><xsl:value-of select="'lel'"/></xsl:when>
            <xsl:when test="$marcrel = 'lender'"><xsl:value-of select="'len'"/></xsl:when>
            <xsl:when test="$marcrel = 'libelee-appellant'"><xsl:value-of select="'let'"/></xsl:when>
            <xsl:when test="$marcrel = 'libelant-appellee'"><xsl:value-of select="'lie'"/></xsl:when>
            <xsl:when test="$marcrel = 'libelant'"><xsl:value-of select="'lil'"/></xsl:when>
            <xsl:when test="$marcrel = 'libelant-appellant'"><xsl:value-of select="'lit'"/></xsl:when>
            <xsl:when test="$marcrel = 'licensee'"><xsl:value-of select="'lse'"/></xsl:when>
            <xsl:when test="$marcrel = 'licensor'"><xsl:value-of select="'lso'"/></xsl:when>
            <xsl:when test="$marcrel = 'lithographer'"><xsl:value-of select="'ltg'"/></xsl:when>
            <xsl:when test="$marcrel = 'lyricist'"><xsl:value-of select="'lyr'"/></xsl:when>
            <xsl:when test="$marcrel = 'medium'"><xsl:value-of select="'med'"/></xsl:when>
            <xsl:when test="$marcrel = 'manufacturer'"><xsl:value-of select="'mfr'"/></xsl:when>
            <xsl:when test="$marcrel = 'moderator'"><xsl:value-of select="'mod'"/></xsl:when>
            <xsl:when test="$marcrel = 'monitor'"><xsl:value-of select="'mon'"/></xsl:when>
            <xsl:when test="$marcrel = 'marbler'"><xsl:value-of select="'mrb'"/></xsl:when>
            <xsl:when test="$marcrel = 'metal-engraver'"><xsl:value-of select="'mte'"/></xsl:when>
            <xsl:when test="$marcrel = 'musician'"><xsl:value-of select="'mus'"/></xsl:when>
            <xsl:when test="$marcrel = 'narrator'"><xsl:value-of select="'nrt'"/></xsl:when>
            <xsl:when test="$marcrel = 'opponent'"><xsl:value-of select="'opn'"/></xsl:when>
            <xsl:when test="$marcrel = 'originator'"><xsl:value-of select="'org'"/></xsl:when>
            <xsl:when test="$marcrel = 'organizer'"><xsl:value-of select="'orm'"/></xsl:when>
            <xsl:when test="$marcrel = 'owner'"><xsl:value-of select="'own'"/></xsl:when>
            <xsl:when test="$marcrel = 'panelist'"><xsl:value-of select="'pan'"/></xsl:when>
            <xsl:when test="$marcrel = 'patron'"><xsl:value-of select="'pat'"/></xsl:when>
            <xsl:when test="$marcrel = 'publisher'"><xsl:value-of select="'pbl'"/></xsl:when>
            <xsl:when test="$marcrel = 'proofreader'"><xsl:value-of select="'pfr'"/></xsl:when>
            <xsl:when test="$marcrel = 'photographer'"><xsl:value-of select="'pht'"/></xsl:when>
            <xsl:when test="$marcrel = 'platemaker'"><xsl:value-of select="'plt'"/></xsl:when>
            <xsl:when test="$marcrel = 'papermaker'"><xsl:value-of select="'ppm'"/></xsl:when>
            <xsl:when test="$marcrel = 'puppeteer'"><xsl:value-of select="'ppt'"/></xsl:when>
            <xsl:when test="$marcrel = 'praeses'"><xsl:value-of select="'pra'"/></xsl:when>
            <xsl:when test="$marcrel = 'presenter'"><xsl:value-of select="'pre'"/></xsl:when>
            <xsl:when test="$marcrel = 'performer'"><xsl:value-of select="'prf'"/></xsl:when>
            <xsl:when test="$marcrel = 'programmer'"><xsl:value-of select="'prg'"/></xsl:when>
            <xsl:when test="$marcrel = 'printmaker'"><xsl:value-of select="'prm'"/></xsl:when>
            <xsl:when test="$marcrel = 'producer'"><xsl:value-of select="'pro'"/></xsl:when>
            <xsl:when test="$marcrel = 'printer'"><xsl:value-of select="'prt'"/></xsl:when>
            <xsl:when test="$marcrel = 'provider'"><xsl:value-of select="'prv'"/></xsl:when>
            <xsl:when test="$marcrel = 'plaintiff-appellee'"><xsl:value-of select="'pte'"/></xsl:when>
            <xsl:when test="$marcrel = 'plaintiff'"><xsl:value-of select="'ptf'"/></xsl:when>
            <xsl:when test="$marcrel = 'plaintiff-appellant'"><xsl:value-of select="'ptt'"/></xsl:when>
            <xsl:when test="$marcrel = 'rubricator'"><xsl:value-of select="'rbr'"/></xsl:when>
            <xsl:when test="$marcrel = 'recordist'"><xsl:value-of select="'rcd'"/></xsl:when>
            <xsl:when test="$marcrel = 'addressee'"><xsl:value-of select="'rcp'"/></xsl:when>
            <xsl:when test="$marcrel = 'redaktor'"><xsl:value-of select="'red'"/></xsl:when>
            <xsl:when test="$marcrel = 'renderer'"><xsl:value-of select="'ren'"/></xsl:when>
            <xsl:when test="$marcrel = 'researcher'"><xsl:value-of select="'res'"/></xsl:when>
            <xsl:when test="$marcrel = 'reviewer'"><xsl:value-of select="'rev'"/></xsl:when>
            <xsl:when test="$marcrel = 'repository'"><xsl:value-of select="'rps'"/></xsl:when>
            <xsl:when test="$marcrel = 'reporter'"><xsl:value-of select="'rpt'"/></xsl:when>
            <xsl:when test="$marcrel = 'respondent-appellee'"><xsl:value-of select="'rse'"/></xsl:when>
            <xsl:when test="$marcrel = 'restager'"><xsl:value-of select="'rsg'"/></xsl:when>
            <xsl:when test="$marcrel = 'respondent'"><xsl:value-of select="'rsp'"/></xsl:when>
            <xsl:when test="$marcrel = 'restorationist'"><xsl:value-of select="'rsr'"/></xsl:when>
            <xsl:when test="$marcrel = 'respondent-appellant'"><xsl:value-of select="'rst'"/></xsl:when>
            <xsl:when test="$marcrel = 'scenarist'"><xsl:value-of select="'sce'"/></xsl:when>
            <xsl:when test="$marcrel = 'sculptor'"><xsl:value-of select="'scl'"/></xsl:when>
            <xsl:when test="$marcrel = 'scribe'"><xsl:value-of select="'scr'"/></xsl:when>
            <xsl:when test="$marcrel = 'secretary'"><xsl:value-of select="'sec'"/></xsl:when>
            <xsl:when test="$marcrel = 'signer'"><xsl:value-of select="'sgn'"/></xsl:when>
            <xsl:when test="$marcrel = 'seller'"><xsl:value-of select="'sll'"/></xsl:when>
            <xsl:when test="$marcrel = 'singer'"><xsl:value-of select="'sng'"/></xsl:when>
            <xsl:when test="$marcrel = 'speaker'"><xsl:value-of select="'spk'"/></xsl:when>
            <xsl:when test="$marcrel = 'sponsor'"><xsl:value-of select="'spn'"/></xsl:when>
            <xsl:when test="$marcrel = 'surveyor'"><xsl:value-of select="'srv'"/></xsl:when>
            <xsl:when test="$marcrel = 'setting'"><xsl:value-of select="'stg'"/></xsl:when>
            <xsl:when test="$marcrel = 'storyteller'"><xsl:value-of select="'stl'"/></xsl:when>
            <xsl:when test="$marcrel = 'stereotyper'"><xsl:value-of select="'str'"/></xsl:when>
            <xsl:when test="$marcrel = 'teacher'"><xsl:value-of select="'tch'"/></xsl:when>
            <xsl:when test="$marcrel = 'transcriber'"><xsl:value-of select="'trc'"/></xsl:when>
            <xsl:when test="$marcrel = 'translator'"><xsl:value-of select="'trl'"/></xsl:when>
            <xsl:when test="$marcrel = 'typographer'"><xsl:value-of select="'tyg'"/></xsl:when>
            <xsl:when test="$marcrel = 'videographer'"><xsl:value-of select="'vdg'"/></xsl:when>
            <xsl:when test="$marcrel = 'woodcutter'"><xsl:value-of select="'wdc'"/></xsl:when>
            <xsl:when test="$marcrel = 'witness'"><xsl:value-of select="'wit'"/></xsl:when>
            <xsl:otherwise><xsl:value-of select="'oth'"/></xsl:otherwise>
        </xsl:choose>
    </xsl:function>
    
    <xsl:function name="nlb:marcrel-to-role" as="xs:string">
        <xsl:param name="role" as="xs:string"/>
        <xsl:choose>
            <xsl:when test="$role = 'abr'"><xsl:value-of select="'abridger'"/></xsl:when>
            <xsl:when test="$role = 'act'"><xsl:value-of select="'actor'"/></xsl:when>
            <xsl:when test="$role = 'adp'"><xsl:value-of select="'adapter'"/></xsl:when>
            <xsl:when test="$role = 'anl'"><xsl:value-of select="'analyst'"/></xsl:when>
            <xsl:when test="$role = 'anm'"><xsl:value-of select="'animator'"/></xsl:when>
            <xsl:when test="$role = 'ann'"><xsl:value-of select="'annotator'"/></xsl:when>
            <xsl:when test="$role = 'ape'"><xsl:value-of select="'appellee'"/></xsl:when>
            <xsl:when test="$role = 'apl'"><xsl:value-of select="'appellant'"/></xsl:when>
            <xsl:when test="$role = 'app'"><xsl:value-of select="'applicant'"/></xsl:when>
            <xsl:when test="$role = 'arc'"><xsl:value-of select="'architect'"/></xsl:when>
            <xsl:when test="$role = 'arr'"><xsl:value-of select="'arranger'"/></xsl:when>
            <xsl:when test="$role = 'art'"><xsl:value-of select="'artist'"/></xsl:when>
            <xsl:when test="$role = 'asg'"><xsl:value-of select="'assignee'"/></xsl:when>
            <xsl:when test="$role = 'ato'"><xsl:value-of select="'autographer'"/></xsl:when>
            <xsl:when test="$role = 'auc'"><xsl:value-of select="'auctioneer'"/></xsl:when>
            <xsl:when test="$role = 'aus'"><xsl:value-of select="'screenwriter'"/></xsl:when>
            <xsl:when test="$role = 'aut'"><xsl:value-of select="'author'"/></xsl:when>
            <xsl:when test="$role = 'bnd'"><xsl:value-of select="'binder'"/></xsl:when>
            <xsl:when test="$role = 'brd'"><xsl:value-of select="'broadcaster'"/></xsl:when>
            <xsl:when test="$role = 'bsl'"><xsl:value-of select="'bookseller'"/></xsl:when>
            <xsl:when test="$role = 'cas'"><xsl:value-of select="'caster'"/></xsl:when>
            <xsl:when test="$role = 'ccp'"><xsl:value-of select="'conceptor'"/></xsl:when>
            <xsl:when test="$role = 'chr'"><xsl:value-of select="'choreographer'"/></xsl:when>
            <xsl:when test="$role = 'cli'"><xsl:value-of select="'client'"/></xsl:when>
            <xsl:when test="$role = 'cll'"><xsl:value-of select="'calligrapher'"/></xsl:when>
            <xsl:when test="$role = 'clr'"><xsl:value-of select="'colorist'"/></xsl:when>
            <xsl:when test="$role = 'clt'"><xsl:value-of select="'collotyper'"/></xsl:when>
            <xsl:when test="$role = 'cmm'"><xsl:value-of select="'commentator'"/></xsl:when>
            <xsl:when test="$role = 'cmp'"><xsl:value-of select="'composer'"/></xsl:when>
            <xsl:when test="$role = 'cmt'"><xsl:value-of select="'compositor'"/></xsl:when>
            <xsl:when test="$role = 'cnd'"><xsl:value-of select="'conductor'"/></xsl:when>
            <xsl:when test="$role = 'cng'"><xsl:value-of select="'cinematographer'"/></xsl:when>
            <xsl:when test="$role = 'cns'"><xsl:value-of select="'censor'"/></xsl:when>
            <xsl:when test="$role = 'coe'"><xsl:value-of select="'contestant-appellee'"/></xsl:when>
            <xsl:when test="$role = 'col'"><xsl:value-of select="'collector'"/></xsl:when>
            <xsl:when test="$role = 'com'"><xsl:value-of select="'compiler'"/></xsl:when>
            <xsl:when test="$role = 'con'"><xsl:value-of select="'conservator'"/></xsl:when>
            <xsl:when test="$role = 'cos'"><xsl:value-of select="'contestant'"/></xsl:when>
            <xsl:when test="$role = 'cot'"><xsl:value-of select="'contestant-appellant'"/></xsl:when>
            <xsl:when test="$role = 'cpe'"><xsl:value-of select="'complainant-appellee'"/></xsl:when>
            <xsl:when test="$role = 'cpl'"><xsl:value-of select="'complainant'"/></xsl:when>
            <xsl:when test="$role = 'cpt'"><xsl:value-of select="'complainant-appellant'"/></xsl:when>
            <xsl:when test="$role = 'cre'"><xsl:value-of select="'creator'"/></xsl:when>
            <xsl:when test="$role = 'crp'"><xsl:value-of select="'correspondent'"/></xsl:when>
            <xsl:when test="$role = 'crr'"><xsl:value-of select="'corrector'"/></xsl:when>
            <xsl:when test="$role = 'csl'"><xsl:value-of select="'consultant'"/></xsl:when>
            <xsl:when test="$role = 'ctb'"><xsl:value-of select="'contributor'"/></xsl:when>
            <xsl:when test="$role = 'cte'"><xsl:value-of select="'contestee-appellee'"/></xsl:when>
            <xsl:when test="$role = 'ctg'"><xsl:value-of select="'cartographer'"/></xsl:when>
            <xsl:when test="$role = 'ctr'"><xsl:value-of select="'contractor'"/></xsl:when>
            <xsl:when test="$role = 'cts'"><xsl:value-of select="'contestee'"/></xsl:when>
            <xsl:when test="$role = 'ctt'"><xsl:value-of select="'contestee-appellant'"/></xsl:when>
            <xsl:when test="$role = 'cur'"><xsl:value-of select="'curator'"/></xsl:when>
            <xsl:when test="$role = 'dfd'"><xsl:value-of select="'defendant'"/></xsl:when>
            <xsl:when test="$role = 'dfe'"><xsl:value-of select="'defendant-appellee'"/></xsl:when>
            <xsl:when test="$role = 'dft'"><xsl:value-of select="'defendant-appellant'"/></xsl:when>
            <xsl:when test="$role = 'dis'"><xsl:value-of select="'dissertant'"/></xsl:when>
            <xsl:when test="$role = 'dln'"><xsl:value-of select="'delineator'"/></xsl:when>
            <xsl:when test="$role = 'dnc'"><xsl:value-of select="'dancer'"/></xsl:when>
            <xsl:when test="$role = 'dnr'"><xsl:value-of select="'donor'"/></xsl:when>
            <xsl:when test="$role = 'dpc'"><xsl:value-of select="'depicted'"/></xsl:when>
            <xsl:when test="$role = 'dpt'"><xsl:value-of select="'depositor'"/></xsl:when>
            <xsl:when test="$role = 'drm'"><xsl:value-of select="'draftsman'"/></xsl:when>
            <xsl:when test="$role = 'drt'"><xsl:value-of select="'director'"/></xsl:when>
            <xsl:when test="$role = 'dsr'"><xsl:value-of select="'designer'"/></xsl:when>
            <xsl:when test="$role = 'dst'"><xsl:value-of select="'distributor'"/></xsl:when>
            <xsl:when test="$role = 'dte'"><xsl:value-of select="'dedicatee'"/></xsl:when>
            <xsl:when test="$role = 'dto'"><xsl:value-of select="'dedicator'"/></xsl:when>
            <xsl:when test="$role = 'edt'"><xsl:value-of select="'editor'"/></xsl:when>
            <xsl:when test="$role = 'egr'"><xsl:value-of select="'engraver'"/></xsl:when>
            <xsl:when test="$role = 'elg'"><xsl:value-of select="'electrician'"/></xsl:when>
            <xsl:when test="$role = 'elt'"><xsl:value-of select="'electrotyper'"/></xsl:when>
            <xsl:when test="$role = 'eng'"><xsl:value-of select="'engineer'"/></xsl:when>
            <xsl:when test="$role = 'etr'"><xsl:value-of select="'etcher'"/></xsl:when>
            <xsl:when test="$role = 'exp'"><xsl:value-of select="'expert'"/></xsl:when>
            <xsl:when test="$role = 'fac'"><xsl:value-of select="'facsimilist'"/></xsl:when>
            <xsl:when test="$role = 'fmk'"><xsl:value-of select="'filmmaker'"/></xsl:when>
            <xsl:when test="$role = 'fnd'"><xsl:value-of select="'funder'"/></xsl:when>
            <xsl:when test="$role = 'frg'"><xsl:value-of select="'forger'"/></xsl:when>
            <xsl:when test="$role = 'hnr'"><xsl:value-of select="'honoree'"/></xsl:when>
            <xsl:when test="$role = 'hst'"><xsl:value-of select="'host'"/></xsl:when>
            <xsl:when test="$role = 'ill'"><xsl:value-of select="'illustrator'"/></xsl:when>
            <xsl:when test="$role = 'ilu'"><xsl:value-of select="'illuminator'"/></xsl:when>
            <xsl:when test="$role = 'ins'"><xsl:value-of select="'inscriber'"/></xsl:when>
            <xsl:when test="$role = 'inv'"><xsl:value-of select="'inventor'"/></xsl:when>
            <xsl:when test="$role = 'itr'"><xsl:value-of select="'instrumentalist'"/></xsl:when>
            <xsl:when test="$role = 'ive'"><xsl:value-of select="'interviewee'"/></xsl:when>
            <xsl:when test="$role = 'ivr'"><xsl:value-of select="'interviewer'"/></xsl:when>
            <xsl:when test="$role = 'jud'"><xsl:value-of select="'judge'"/></xsl:when>
            <xsl:when test="$role = 'lbr'"><xsl:value-of select="'laboratory'"/></xsl:when>
            <xsl:when test="$role = 'lbt'"><xsl:value-of select="'librettist'"/></xsl:when>
            <xsl:when test="$role = 'led'"><xsl:value-of select="'lead'"/></xsl:when>
            <xsl:when test="$role = 'lee'"><xsl:value-of select="'libelee-appellee'"/></xsl:when>
            <xsl:when test="$role = 'lel'"><xsl:value-of select="'libelee'"/></xsl:when>
            <xsl:when test="$role = 'len'"><xsl:value-of select="'lender'"/></xsl:when>
            <xsl:when test="$role = 'let'"><xsl:value-of select="'libelee-appellant'"/></xsl:when>
            <xsl:when test="$role = 'lie'"><xsl:value-of select="'libelant-appellee'"/></xsl:when>
            <xsl:when test="$role = 'lil'"><xsl:value-of select="'libelant'"/></xsl:when>
            <xsl:when test="$role = 'lit'"><xsl:value-of select="'libelant-appellant'"/></xsl:when>
            <xsl:when test="$role = 'lse'"><xsl:value-of select="'licensee'"/></xsl:when>
            <xsl:when test="$role = 'lso'"><xsl:value-of select="'licensor'"/></xsl:when>
            <xsl:when test="$role = 'ltg'"><xsl:value-of select="'lithographer'"/></xsl:when>
            <xsl:when test="$role = 'lyr'"><xsl:value-of select="'lyricist'"/></xsl:when>
            <xsl:when test="$role = 'med'"><xsl:value-of select="'medium'"/></xsl:when>
            <xsl:when test="$role = 'mfr'"><xsl:value-of select="'manufacturer'"/></xsl:when>
            <xsl:when test="$role = 'mod'"><xsl:value-of select="'moderator'"/></xsl:when>
            <xsl:when test="$role = 'mon'"><xsl:value-of select="'monitor'"/></xsl:when>
            <xsl:when test="$role = 'mrb'"><xsl:value-of select="'marbler'"/></xsl:when>
            <xsl:when test="$role = 'mte'"><xsl:value-of select="'metal-engraver'"/></xsl:when>
            <xsl:when test="$role = 'mus'"><xsl:value-of select="'musician'"/></xsl:when>
            <xsl:when test="$role = 'nrt'"><xsl:value-of select="'narrator'"/></xsl:when>
            <xsl:when test="$role = 'opn'"><xsl:value-of select="'opponent'"/></xsl:when>
            <xsl:when test="$role = 'org'"><xsl:value-of select="'originator'"/></xsl:when>
            <xsl:when test="$role = 'orm'"><xsl:value-of select="'organizer'"/></xsl:when>
            <xsl:when test="$role = 'own'"><xsl:value-of select="'owner'"/></xsl:when>
            <xsl:when test="$role = 'pan'"><xsl:value-of select="'panelist'"/></xsl:when>
            <xsl:when test="$role = 'pat'"><xsl:value-of select="'patron'"/></xsl:when>
            <xsl:when test="$role = 'pbl'"><xsl:value-of select="'publisher'"/></xsl:when>
            <xsl:when test="$role = 'pfr'"><xsl:value-of select="'proofreader'"/></xsl:when>
            <xsl:when test="$role = 'pht'"><xsl:value-of select="'photographer'"/></xsl:when>
            <xsl:when test="$role = 'plt'"><xsl:value-of select="'platemaker'"/></xsl:when>
            <xsl:when test="$role = 'ppm'"><xsl:value-of select="'papermaker'"/></xsl:when>
            <xsl:when test="$role = 'ppt'"><xsl:value-of select="'puppeteer'"/></xsl:when>
            <xsl:when test="$role = 'pra'"><xsl:value-of select="'praeses'"/></xsl:when>
            <xsl:when test="$role = 'pre'"><xsl:value-of select="'presenter'"/></xsl:when>
            <xsl:when test="$role = 'prf'"><xsl:value-of select="'performer'"/></xsl:when>
            <xsl:when test="$role = 'prg'"><xsl:value-of select="'programmer'"/></xsl:when>
            <xsl:when test="$role = 'prm'"><xsl:value-of select="'printmaker'"/></xsl:when>
            <xsl:when test="$role = 'pro'"><xsl:value-of select="'producer'"/></xsl:when>
            <xsl:when test="$role = 'prt'"><xsl:value-of select="'printer'"/></xsl:when>
            <xsl:when test="$role = 'prv'"><xsl:value-of select="'provider'"/></xsl:when>
            <xsl:when test="$role = 'pte'"><xsl:value-of select="'plaintiff-appellee'"/></xsl:when>
            <xsl:when test="$role = 'ptf'"><xsl:value-of select="'plaintiff'"/></xsl:when>
            <xsl:when test="$role = 'ptt'"><xsl:value-of select="'plaintiff-appellant'"/></xsl:when>
            <xsl:when test="$role = 'rbr'"><xsl:value-of select="'rubricator'"/></xsl:when>
            <xsl:when test="$role = 'rcd'"><xsl:value-of select="'recordist'"/></xsl:when>
            <xsl:when test="$role = 'rcp'"><xsl:value-of select="'addressee'"/></xsl:when>
            <xsl:when test="$role = 'red'"><xsl:value-of select="'redaktor'"/></xsl:when>
            <xsl:when test="$role = 'ren'"><xsl:value-of select="'renderer'"/></xsl:when>
            <xsl:when test="$role = 'res'"><xsl:value-of select="'researcher'"/></xsl:when>
            <xsl:when test="$role = 'rev'"><xsl:value-of select="'reviewer'"/></xsl:when>
            <xsl:when test="$role = 'rps'"><xsl:value-of select="'repository'"/></xsl:when>
            <xsl:when test="$role = 'rpt'"><xsl:value-of select="'reporter'"/></xsl:when>
            <xsl:when test="$role = 'rse'"><xsl:value-of select="'respondent-appellee'"/></xsl:when>
            <xsl:when test="$role = 'rsg'"><xsl:value-of select="'restager'"/></xsl:when>
            <xsl:when test="$role = 'rsp'"><xsl:value-of select="'respondent'"/></xsl:when>
            <xsl:when test="$role = 'rsr'"><xsl:value-of select="'restorationist'"/></xsl:when>
            <xsl:when test="$role = 'rst'"><xsl:value-of select="'respondent-appellant'"/></xsl:when>
            <xsl:when test="$role = 'sce'"><xsl:value-of select="'scenarist'"/></xsl:when>
            <xsl:when test="$role = 'scl'"><xsl:value-of select="'sculptor'"/></xsl:when>
            <xsl:when test="$role = 'scr'"><xsl:value-of select="'scribe'"/></xsl:when>
            <xsl:when test="$role = 'sec'"><xsl:value-of select="'secretary'"/></xsl:when>
            <xsl:when test="$role = 'sgn'"><xsl:value-of select="'signer'"/></xsl:when>
            <xsl:when test="$role = 'sll'"><xsl:value-of select="'seller'"/></xsl:when>
            <xsl:when test="$role = 'sng'"><xsl:value-of select="'singer'"/></xsl:when>
            <xsl:when test="$role = 'spk'"><xsl:value-of select="'speaker'"/></xsl:when>
            <xsl:when test="$role = 'spn'"><xsl:value-of select="'sponsor'"/></xsl:when>
            <xsl:when test="$role = 'srv'"><xsl:value-of select="'surveyor'"/></xsl:when>
            <xsl:when test="$role = 'stg'"><xsl:value-of select="'setting'"/></xsl:when>
            <xsl:when test="$role = 'stl'"><xsl:value-of select="'storyteller'"/></xsl:when>
            <xsl:when test="$role = 'str'"><xsl:value-of select="'stereotyper'"/></xsl:when>
            <xsl:when test="$role = 'tch'"><xsl:value-of select="'teacher'"/></xsl:when>
            <xsl:when test="$role = 'trc'"><xsl:value-of select="'transcriber'"/></xsl:when>
            <xsl:when test="$role = 'trl'"><xsl:value-of select="'translator'"/></xsl:when>
            <xsl:when test="$role = 'tyg'"><xsl:value-of select="'typographer'"/></xsl:when>
            <xsl:when test="$role = 'vdg'"><xsl:value-of select="'videographer'"/></xsl:when>
            <xsl:when test="$role = 'wdc'"><xsl:value-of select="'woodcutter'"/></xsl:when>
            <xsl:when test="$role = 'wit'"><xsl:value-of select="'witness'"/></xsl:when>
            <xsl:otherwise><xsl:value-of select="'other'"/></xsl:otherwise>
        </xsl:choose>
    </xsl:function>
    
</xsl:stylesheet>