<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:nlb="http://www.nlb.no/"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                exclude-result-prefixes="#all"
                version="2.0">
    
    <xsl:function name="nlb:role-to-marcrel" as="xs:string">
        <xsl:param name="role" as="xs:string"/>
        <xsl:choose>
            <xsl:when test="$role = 'abridger'"><xsl:value-of select="'abr'"/></xsl:when>
            <xsl:when test="$role = 'art_copyist'"><xsl:value-of select="'acp'"/></xsl:when>
            <xsl:when test="$role = 'actor'"><xsl:value-of select="'act'"/></xsl:when>
            <xsl:when test="$role = 'art_director'"><xsl:value-of select="'adi'"/></xsl:when>
            <xsl:when test="$role = 'adapter'"><xsl:value-of select="'adp'"/></xsl:when>
            <xsl:when test="$role = 'author_of_afterword_or_colophon'"><xsl:value-of select="'aft'"/></xsl:when>
            <xsl:when test="$role = 'analyst'"><xsl:value-of select="'anl'"/></xsl:when>
            <xsl:when test="$role = 'animator'"><xsl:value-of select="'anm'"/></xsl:when>
            <xsl:when test="$role = 'annotator'"><xsl:value-of select="'ann'"/></xsl:when>
            <xsl:when test="$role = 'bibliographic_antecedent'"><xsl:value-of select="'ant'"/></xsl:when>
            <xsl:when test="$role = 'appellee'"><xsl:value-of select="'ape'"/></xsl:when>
            <xsl:when test="$role = 'appellant'"><xsl:value-of select="'apl'"/></xsl:when>
            <xsl:when test="$role = 'applicant'"><xsl:value-of select="'app'"/></xsl:when>
            <xsl:when test="$role = 'author_in_quotations_or_text_abstracts'"><xsl:value-of select="'aqt'"/></xsl:when>
            <xsl:when test="$role = 'architect'"><xsl:value-of select="'arc'"/></xsl:when>
            <xsl:when test="$role = 'artistic_director'"><xsl:value-of select="'ard'"/></xsl:when>
            <xsl:when test="$role = 'arranger'"><xsl:value-of select="'arr'"/></xsl:when>
            <xsl:when test="$role = 'artist'"><xsl:value-of select="'art'"/></xsl:when>
            <xsl:when test="$role = 'assignee'"><xsl:value-of select="'asg'"/></xsl:when>
            <xsl:when test="$role = 'associated_name'"><xsl:value-of select="'asn'"/></xsl:when>
            <xsl:when test="$role = 'autographer'"><xsl:value-of select="'ato'"/></xsl:when>
            <xsl:when test="$role = 'attributed_name'"><xsl:value-of select="'att'"/></xsl:when>
            <xsl:when test="$role = 'auctioneer'"><xsl:value-of select="'auc'"/></xsl:when>
            <xsl:when test="$role = 'author_of_dialog'"><xsl:value-of select="'aud'"/></xsl:when>
            <xsl:when test="$role = 'author_of_introduction'"><xsl:value-of select="'aui'"/></xsl:when>
            <xsl:when test="$role = 'screenwriter'"><xsl:value-of select="'aus'"/></xsl:when>
            <xsl:when test="$role = 'author'"><xsl:value-of select="'aut'"/></xsl:when>
            <xsl:when test="$role = 'binding_designer'"><xsl:value-of select="'bdd'"/></xsl:when>
            <xsl:when test="$role = 'bookjacket_designer'"><xsl:value-of select="'bjd'"/></xsl:when>
            <xsl:when test="$role = 'book_designer'"><xsl:value-of select="'bkd'"/></xsl:when>
            <xsl:when test="$role = 'book_producer'"><xsl:value-of select="'bkp'"/></xsl:when>
            <xsl:when test="$role = 'blurb_writer'"><xsl:value-of select="'blw'"/></xsl:when>
            <xsl:when test="$role = 'binder'"><xsl:value-of select="'bnd'"/></xsl:when>
            <xsl:when test="$role = 'bookplate_designer'"><xsl:value-of select="'bpd'"/></xsl:when>
            <xsl:when test="$role = 'broadcaster'"><xsl:value-of select="'brd'"/></xsl:when>
            <xsl:when test="$role = 'braille_embosser'"><xsl:value-of select="'brl'"/></xsl:when>
            <xsl:when test="$role = 'bookseller'"><xsl:value-of select="'bsl'"/></xsl:when>
            <xsl:when test="$role = 'caster'"><xsl:value-of select="'cas'"/></xsl:when>
            <xsl:when test="$role = 'conceptor'"><xsl:value-of select="'ccp'"/></xsl:when>
            <xsl:when test="$role = 'choreographer'"><xsl:value-of select="'chr'"/></xsl:when>
            <xsl:when test="$role = 'collaborator'"><xsl:value-of select="'clb'"/></xsl:when>
            <xsl:when test="$role = 'client'"><xsl:value-of select="'cli'"/></xsl:when>
            <xsl:when test="$role = 'calligrapher'"><xsl:value-of select="'cll'"/></xsl:when>
            <xsl:when test="$role = 'colorist'"><xsl:value-of select="'clr'"/></xsl:when>
            <xsl:when test="$role = 'collotyper'"><xsl:value-of select="'clt'"/></xsl:when>
            <xsl:when test="$role = 'commentator'"><xsl:value-of select="'cmm'"/></xsl:when>
            <xsl:when test="$role = 'composer'"><xsl:value-of select="'cmp'"/></xsl:when>
            <xsl:when test="$role = 'compositor'"><xsl:value-of select="'cmt'"/></xsl:when>
            <xsl:when test="$role = 'conductor'"><xsl:value-of select="'cnd'"/></xsl:when>
            <xsl:when test="$role = 'cinematographer'"><xsl:value-of select="'cng'"/></xsl:when>
            <xsl:when test="$role = 'censor'"><xsl:value-of select="'cns'"/></xsl:when>
            <xsl:when test="$role = 'contestant_appellee'"><xsl:value-of select="'coe'"/></xsl:when>
            <xsl:when test="$role = 'collector'"><xsl:value-of select="'col'"/></xsl:when>
            <xsl:when test="$role = 'compiler'"><xsl:value-of select="'com'"/></xsl:when>
            <xsl:when test="$role = 'conservator'"><xsl:value-of select="'con'"/></xsl:when>
            <xsl:when test="$role = 'collection_registrar'"><xsl:value-of select="'cor'"/></xsl:when>
            <xsl:when test="$role = 'contestant'"><xsl:value-of select="'cos'"/></xsl:when>
            <xsl:when test="$role = 'contestant_appellant'"><xsl:value-of select="'cot'"/></xsl:when>
            <xsl:when test="$role = 'court_governed'"><xsl:value-of select="'cou'"/></xsl:when>
            <xsl:when test="$role = 'cover_designer'"><xsl:value-of select="'cov'"/></xsl:when>
            <xsl:when test="$role = 'copyright_claimant'"><xsl:value-of select="'cpc'"/></xsl:when>
            <xsl:when test="$role = 'complainant_appellee'"><xsl:value-of select="'cpe'"/></xsl:when>
            <xsl:when test="$role = 'copyright_holder'"><xsl:value-of select="'cph'"/></xsl:when>
            <xsl:when test="$role = 'complainant'"><xsl:value-of select="'cpl'"/></xsl:when>
            <xsl:when test="$role = 'complainant_appellant'"><xsl:value-of select="'cpt'"/></xsl:when>
            <xsl:when test="$role = 'creator'"><xsl:value-of select="'cre'"/></xsl:when>
            <xsl:when test="$role = 'correspondent'"><xsl:value-of select="'crp'"/></xsl:when>
            <xsl:when test="$role = 'corrector'"><xsl:value-of select="'crr'"/></xsl:when>
            <xsl:when test="$role = 'court_reporter'"><xsl:value-of select="'crt'"/></xsl:when>
            <xsl:when test="$role = 'consultant'"><xsl:value-of select="'csl'"/></xsl:when>
            <xsl:when test="$role = 'consultant_to_a_project'"><xsl:value-of select="'csp'"/></xsl:when>
            <xsl:when test="$role = 'costume_designer'"><xsl:value-of select="'cst'"/></xsl:when>
            <xsl:when test="$role = 'contributor'"><xsl:value-of select="'ctb'"/></xsl:when>
            <xsl:when test="$role = 'contestee_appellee'"><xsl:value-of select="'cte'"/></xsl:when>
            <xsl:when test="$role = 'cartographer'"><xsl:value-of select="'ctg'"/></xsl:when>
            <xsl:when test="$role = 'contractor'"><xsl:value-of select="'ctr'"/></xsl:when>
            <xsl:when test="$role = 'contestee'"><xsl:value-of select="'cts'"/></xsl:when>
            <xsl:when test="$role = 'contestee_appellant'"><xsl:value-of select="'ctt'"/></xsl:when>
            <xsl:when test="$role = 'curator'"><xsl:value-of select="'cur'"/></xsl:when>
            <xsl:when test="$role = 'commentator_for_written_text'"><xsl:value-of select="'cwt'"/></xsl:when>
            <xsl:when test="$role = 'distribution_place'"><xsl:value-of select="'dbp'"/></xsl:when>
            <xsl:when test="$role = 'defendant'"><xsl:value-of select="'dfd'"/></xsl:when>
            <xsl:when test="$role = 'defendant_appellee'"><xsl:value-of select="'dfe'"/></xsl:when>
            <xsl:when test="$role = 'defendant_appellant'"><xsl:value-of select="'dft'"/></xsl:when>
            <xsl:when test="$role = 'degree_granting_institution'"><xsl:value-of select="'dgg'"/></xsl:when>
            <xsl:when test="$role = 'degree_supervisor'"><xsl:value-of select="'dgs'"/></xsl:when>
            <xsl:when test="$role = 'dissertant'"><xsl:value-of select="'dis'"/></xsl:when>
            <xsl:when test="$role = 'delineator'"><xsl:value-of select="'dln'"/></xsl:when>
            <xsl:when test="$role = 'dancer'"><xsl:value-of select="'dnc'"/></xsl:when>
            <xsl:when test="$role = 'donor'"><xsl:value-of select="'dnr'"/></xsl:when>
            <xsl:when test="$role = 'depicted'"><xsl:value-of select="'dpc'"/></xsl:when>
            <xsl:when test="$role = 'depositor'"><xsl:value-of select="'dpt'"/></xsl:when>
            <xsl:when test="$role = 'draftsman'"><xsl:value-of select="'drm'"/></xsl:when>
            <xsl:when test="$role = 'director'"><xsl:value-of select="'drt'"/></xsl:when>
            <xsl:when test="$role = 'designer'"><xsl:value-of select="'dsr'"/></xsl:when>
            <xsl:when test="$role = 'distributor'"><xsl:value-of select="'dst'"/></xsl:when>
            <xsl:when test="$role = 'data_contributor'"><xsl:value-of select="'dtc'"/></xsl:when>
            <xsl:when test="$role = 'dedicatee'"><xsl:value-of select="'dte'"/></xsl:when>
            <xsl:when test="$role = 'data_manager'"><xsl:value-of select="'dtm'"/></xsl:when>
            <xsl:when test="$role = 'dedicator'"><xsl:value-of select="'dto'"/></xsl:when>
            <xsl:when test="$role = 'dubious_author'"><xsl:value-of select="'dub'"/></xsl:when>
            <xsl:when test="$role = 'editor_of_compilation'"><xsl:value-of select="'edc'"/></xsl:when>
            <xsl:when test="$role = 'editor_of_moving_image_work'"><xsl:value-of select="'edm'"/></xsl:when>
            <xsl:when test="$role = 'editor'"><xsl:value-of select="'edt'"/></xsl:when>
            <xsl:when test="$role = 'engraver'"><xsl:value-of select="'egr'"/></xsl:when>
            <xsl:when test="$role = 'electrician'"><xsl:value-of select="'elg'"/></xsl:when>
            <xsl:when test="$role = 'electrotyper'"><xsl:value-of select="'elt'"/></xsl:when>
            <xsl:when test="$role = 'engineer'"><xsl:value-of select="'eng'"/></xsl:when>
            <xsl:when test="$role = 'enacting_jurisdiction'"><xsl:value-of select="'enj'"/></xsl:when>
            <xsl:when test="$role = 'etcher'"><xsl:value-of select="'etr'"/></xsl:when>
            <xsl:when test="$role = 'event_place'"><xsl:value-of select="'evp'"/></xsl:when>
            <xsl:when test="$role = 'expert'"><xsl:value-of select="'exp'"/></xsl:when>
            <xsl:when test="$role = 'facsimilist'"><xsl:value-of select="'fac'"/></xsl:when>
            <xsl:when test="$role = 'film_distributor'"><xsl:value-of select="'fds'"/></xsl:when>
            <xsl:when test="$role = 'field_director'"><xsl:value-of select="'fld'"/></xsl:when>
            <xsl:when test="$role = 'film_editor'"><xsl:value-of select="'flm'"/></xsl:when>
            <xsl:when test="$role = 'film_director'"><xsl:value-of select="'fmd'"/></xsl:when>
            <xsl:when test="$role = 'filmmaker'"><xsl:value-of select="'fmk'"/></xsl:when>
            <xsl:when test="$role = 'former_owner'"><xsl:value-of select="'fmo'"/></xsl:when>
            <xsl:when test="$role = 'film_producer'"><xsl:value-of select="'fmp'"/></xsl:when>
            <xsl:when test="$role = 'funder'"><xsl:value-of select="'fnd'"/></xsl:when>
            <xsl:when test="$role = 'first_party'"><xsl:value-of select="'fpy'"/></xsl:when>
            <xsl:when test="$role = 'forger'"><xsl:value-of select="'frg'"/></xsl:when>
            <xsl:when test="$role = 'geographic_information_specialist'"><xsl:value-of select="'gis'"/></xsl:when>
            <xsl:when test="$role = 'graphic_technician'"><xsl:value-of select="'grt'"/></xsl:when>
            <xsl:when test="$role = 'host_institution'"><xsl:value-of select="'his'"/></xsl:when>
            <xsl:when test="$role = 'honoree'"><xsl:value-of select="'hnr'"/></xsl:when>
            <xsl:when test="$role = 'host'"><xsl:value-of select="'hst'"/></xsl:when>
            <xsl:when test="$role = 'illustrator'"><xsl:value-of select="'ill'"/></xsl:when>
            <xsl:when test="$role = 'illuminator'"><xsl:value-of select="'ilu'"/></xsl:when>
            <xsl:when test="$role = 'inscriber'"><xsl:value-of select="'ins'"/></xsl:when>
            <xsl:when test="$role = 'inventor'"><xsl:value-of select="'inv'"/></xsl:when>
            <xsl:when test="$role = 'issuing_body'"><xsl:value-of select="'isb'"/></xsl:when>
            <xsl:when test="$role = 'instrumentalist'"><xsl:value-of select="'itr'"/></xsl:when>
            <xsl:when test="$role = 'interviewee'"><xsl:value-of select="'ive'"/></xsl:when>
            <xsl:when test="$role = 'interviewer'"><xsl:value-of select="'ivr'"/></xsl:when>
            <xsl:when test="$role = 'judge'"><xsl:value-of select="'jud'"/></xsl:when>
            <xsl:when test="$role = 'jurisdiction_governed'"><xsl:value-of select="'jug'"/></xsl:when>
            <xsl:when test="$role = 'laboratory'"><xsl:value-of select="'lbr'"/></xsl:when>
            <xsl:when test="$role = 'librettist'"><xsl:value-of select="'lbt'"/></xsl:when>
            <xsl:when test="$role = 'laboratory_director'"><xsl:value-of select="'ldr'"/></xsl:when>
            <xsl:when test="$role = 'lead'"><xsl:value-of select="'led'"/></xsl:when>
            <xsl:when test="$role = 'libelee_appellee'"><xsl:value-of select="'lee'"/></xsl:when>
            <xsl:when test="$role = 'libelee'"><xsl:value-of select="'lel'"/></xsl:when>
            <xsl:when test="$role = 'lender'"><xsl:value-of select="'len'"/></xsl:when>
            <xsl:when test="$role = 'libelee_appellant'"><xsl:value-of select="'let'"/></xsl:when>
            <xsl:when test="$role = 'lighting_designer'"><xsl:value-of select="'lgd'"/></xsl:when>
            <xsl:when test="$role = 'libelant_appellee'"><xsl:value-of select="'lie'"/></xsl:when>
            <xsl:when test="$role = 'libelant'"><xsl:value-of select="'lil'"/></xsl:when>
            <xsl:when test="$role = 'libelant_appellant'"><xsl:value-of select="'lit'"/></xsl:when>
            <xsl:when test="$role = 'landscape_architect'"><xsl:value-of select="'lsa'"/></xsl:when>
            <xsl:when test="$role = 'licensee'"><xsl:value-of select="'lse'"/></xsl:when>
            <xsl:when test="$role = 'licensor'"><xsl:value-of select="'lso'"/></xsl:when>
            <xsl:when test="$role = 'lithographer'"><xsl:value-of select="'ltg'"/></xsl:when>
            <xsl:when test="$role = 'lyricist'"><xsl:value-of select="'lyr'"/></xsl:when>
            <xsl:when test="$role = 'music_copyist'"><xsl:value-of select="'mcp'"/></xsl:when>
            <xsl:when test="$role = 'metadata_contact'"><xsl:value-of select="'mdc'"/></xsl:when>
            <xsl:when test="$role = 'medium'"><xsl:value-of select="'med'"/></xsl:when>
            <xsl:when test="$role = 'manufacture_place'"><xsl:value-of select="'mfp'"/></xsl:when>
            <xsl:when test="$role = 'manufacturer'"><xsl:value-of select="'mfr'"/></xsl:when>
            <xsl:when test="$role = 'moderator'"><xsl:value-of select="'mod'"/></xsl:when>
            <xsl:when test="$role = 'monitor'"><xsl:value-of select="'mon'"/></xsl:when>
            <xsl:when test="$role = 'marbler'"><xsl:value-of select="'mrb'"/></xsl:when>
            <xsl:when test="$role = 'markup_editor'"><xsl:value-of select="'mrk'"/></xsl:when>
            <xsl:when test="$role = 'musical_director'"><xsl:value-of select="'msd'"/></xsl:when>
            <xsl:when test="$role = 'metal_engraver'"><xsl:value-of select="'mte'"/></xsl:when>
            <xsl:when test="$role = 'minute_taker'"><xsl:value-of select="'mtk'"/></xsl:when>
            <xsl:when test="$role = 'musician'"><xsl:value-of select="'mus'"/></xsl:when>
            <xsl:when test="$role = 'narrator'"><xsl:value-of select="'nrt'"/></xsl:when>
            <xsl:when test="$role = 'opponent'"><xsl:value-of select="'opn'"/></xsl:when>
            <xsl:when test="$role = 'originator'"><xsl:value-of select="'org'"/></xsl:when>
            <xsl:when test="$role = 'organizer'"><xsl:value-of select="'orm'"/></xsl:when>
            <xsl:when test="$role = 'onscreen_presenter'"><xsl:value-of select="'osp'"/></xsl:when>
            <xsl:when test="$role = 'owner'"><xsl:value-of select="'own'"/></xsl:when>
            <xsl:when test="$role = 'panelist'"><xsl:value-of select="'pan'"/></xsl:when>
            <xsl:when test="$role = 'patron'"><xsl:value-of select="'pat'"/></xsl:when>
            <xsl:when test="$role = 'publishing_director'"><xsl:value-of select="'pbd'"/></xsl:when>
            <xsl:when test="$role = 'publisher'"><xsl:value-of select="'pbl'"/></xsl:when>
            <xsl:when test="$role = 'project_director'"><xsl:value-of select="'pdr'"/></xsl:when>
            <xsl:when test="$role = 'proofreader'"><xsl:value-of select="'pfr'"/></xsl:when>
            <xsl:when test="$role = 'photographer'"><xsl:value-of select="'pht'"/></xsl:when>
            <xsl:when test="$role = 'platemaker'"><xsl:value-of select="'plt'"/></xsl:when>
            <xsl:when test="$role = 'permitting_agency'"><xsl:value-of select="'pma'"/></xsl:when>
            <xsl:when test="$role = 'production_manager'"><xsl:value-of select="'pmn'"/></xsl:when>
            <xsl:when test="$role = 'printer_of_plates'"><xsl:value-of select="'pop'"/></xsl:when>
            <xsl:when test="$role = 'papermaker'"><xsl:value-of select="'ppm'"/></xsl:when>
            <xsl:when test="$role = 'puppeteer'"><xsl:value-of select="'ppt'"/></xsl:when>
            <xsl:when test="$role = 'praeses'"><xsl:value-of select="'pra'"/></xsl:when>
            <xsl:when test="$role = 'process_contact'"><xsl:value-of select="'prc'"/></xsl:when>
            <xsl:when test="$role = 'production_personnel'"><xsl:value-of select="'prd'"/></xsl:when>
            <xsl:when test="$role = 'presenter'"><xsl:value-of select="'pre'"/></xsl:when>
            <xsl:when test="$role = 'performer'"><xsl:value-of select="'prf'"/></xsl:when>
            <xsl:when test="$role = 'programmer'"><xsl:value-of select="'prg'"/></xsl:when>
            <xsl:when test="$role = 'printmaker'"><xsl:value-of select="'prm'"/></xsl:when>
            <xsl:when test="$role = 'production_company'"><xsl:value-of select="'prn'"/></xsl:when>
            <xsl:when test="$role = 'producer'"><xsl:value-of select="'pro'"/></xsl:when>
            <xsl:when test="$role = 'production_place'"><xsl:value-of select="'prp'"/></xsl:when>
            <xsl:when test="$role = 'production_designer'"><xsl:value-of select="'prs'"/></xsl:when>
            <xsl:when test="$role = 'printer'"><xsl:value-of select="'prt'"/></xsl:when>
            <xsl:when test="$role = 'provider'"><xsl:value-of select="'prv'"/></xsl:when>
            <xsl:when test="$role = 'patent_applicant'"><xsl:value-of select="'pta'"/></xsl:when>
            <xsl:when test="$role = 'plaintiff_appellee'"><xsl:value-of select="'pte'"/></xsl:when>
            <xsl:when test="$role = 'plaintiff'"><xsl:value-of select="'ptf'"/></xsl:when>
            <xsl:when test="$role = 'patent_holder'"><xsl:value-of select="'pth'"/></xsl:when>
            <xsl:when test="$role = 'plaintiff_appellant'"><xsl:value-of select="'ptt'"/></xsl:when>
            <xsl:when test="$role = 'publication_place'"><xsl:value-of select="'pup'"/></xsl:when>
            <xsl:when test="$role = 'rubricator'"><xsl:value-of select="'rbr'"/></xsl:when>
            <xsl:when test="$role = 'recordist'"><xsl:value-of select="'rcd'"/></xsl:when>
            <xsl:when test="$role = 'recording_engineer'"><xsl:value-of select="'rce'"/></xsl:when>
            <xsl:when test="$role = 'addressee'"><xsl:value-of select="'rcp'"/></xsl:when>
            <xsl:when test="$role = 'radio_director'"><xsl:value-of select="'rdd'"/></xsl:when>
            <xsl:when test="$role = 'redaktor'"><xsl:value-of select="'red'"/></xsl:when>
            <xsl:when test="$role = 'renderer'"><xsl:value-of select="'ren'"/></xsl:when>
            <xsl:when test="$role = 'researcher'"><xsl:value-of select="'res'"/></xsl:when>
            <xsl:when test="$role = 'reviewer'"><xsl:value-of select="'rev'"/></xsl:when>
            <xsl:when test="$role = 'radio_producer'"><xsl:value-of select="'rpc'"/></xsl:when>
            <xsl:when test="$role = 'repository'"><xsl:value-of select="'rps'"/></xsl:when>
            <xsl:when test="$role = 'reporter'"><xsl:value-of select="'rpt'"/></xsl:when>
            <xsl:when test="$role = 'responsible_party'"><xsl:value-of select="'rpy'"/></xsl:when>
            <xsl:when test="$role = 'respondent_appellee'"><xsl:value-of select="'rse'"/></xsl:when>
            <xsl:when test="$role = 'restager'"><xsl:value-of select="'rsg'"/></xsl:when>
            <xsl:when test="$role = 'respondent'"><xsl:value-of select="'rsp'"/></xsl:when>
            <xsl:when test="$role = 'restorationist'"><xsl:value-of select="'rsr'"/></xsl:when>
            <xsl:when test="$role = 'respondent_appellant'"><xsl:value-of select="'rst'"/></xsl:when>
            <xsl:when test="$role = 'research_team_head'"><xsl:value-of select="'rth'"/></xsl:when>
            <xsl:when test="$role = 'research_team_member'"><xsl:value-of select="'rtm'"/></xsl:when>
            <xsl:when test="$role = 'scientific_advisor'"><xsl:value-of select="'sad'"/></xsl:when>
            <xsl:when test="$role = 'scenarist'"><xsl:value-of select="'sce'"/></xsl:when>
            <xsl:when test="$role = 'sculptor'"><xsl:value-of select="'scl'"/></xsl:when>
            <xsl:when test="$role = 'scribe'"><xsl:value-of select="'scr'"/></xsl:when>
            <xsl:when test="$role = 'sound_designer'"><xsl:value-of select="'sds'"/></xsl:when>
            <xsl:when test="$role = 'secretary'"><xsl:value-of select="'sec'"/></xsl:when>
            <xsl:when test="$role = 'stage_director'"><xsl:value-of select="'sgd'"/></xsl:when>
            <xsl:when test="$role = 'signer'"><xsl:value-of select="'sgn'"/></xsl:when>
            <xsl:when test="$role = 'supporting_host'"><xsl:value-of select="'sht'"/></xsl:when>
            <xsl:when test="$role = 'seller'"><xsl:value-of select="'sll'"/></xsl:when>
            <xsl:when test="$role = 'singer'"><xsl:value-of select="'sng'"/></xsl:when>
            <xsl:when test="$role = 'speaker'"><xsl:value-of select="'spk'"/></xsl:when>
            <xsl:when test="$role = 'sponsor'"><xsl:value-of select="'spn'"/></xsl:when>
            <xsl:when test="$role = 'second_party'"><xsl:value-of select="'spy'"/></xsl:when>
            <xsl:when test="$role = 'surveyor'"><xsl:value-of select="'srv'"/></xsl:when>
            <xsl:when test="$role = 'set_designer'"><xsl:value-of select="'std'"/></xsl:when>
            <xsl:when test="$role = 'setting'"><xsl:value-of select="'stg'"/></xsl:when>
            <xsl:when test="$role = 'storyteller'"><xsl:value-of select="'stl'"/></xsl:when>
            <xsl:when test="$role = 'stage_manager'"><xsl:value-of select="'stm'"/></xsl:when>
            <xsl:when test="$role = 'standards_body'"><xsl:value-of select="'stn'"/></xsl:when>
            <xsl:when test="$role = 'stereotyper'"><xsl:value-of select="'str'"/></xsl:when>
            <xsl:when test="$role = 'technical_director'"><xsl:value-of select="'tcd'"/></xsl:when>
            <xsl:when test="$role = 'teacher'"><xsl:value-of select="'tch'"/></xsl:when>
            <xsl:when test="$role = 'thesis_advisor'"><xsl:value-of select="'ths'"/></xsl:when>
            <xsl:when test="$role = 'television_director'"><xsl:value-of select="'tld'"/></xsl:when>
            <xsl:when test="$role = 'television_producer'"><xsl:value-of select="'tlp'"/></xsl:when>
            <xsl:when test="$role = 'transcriber'"><xsl:value-of select="'trc'"/></xsl:when>
            <xsl:when test="$role = 'translator'"><xsl:value-of select="'trl'"/></xsl:when>
            <xsl:when test="$role = 'type_designer'"><xsl:value-of select="'tyd'"/></xsl:when>
            <xsl:when test="$role = 'typographer'"><xsl:value-of select="'tyg'"/></xsl:when>
            <xsl:when test="$role = 'university_place'"><xsl:value-of select="'uvp'"/></xsl:when>
            <xsl:when test="$role = 'voice_actor'"><xsl:value-of select="'vac'"/></xsl:when>
            <xsl:when test="$role = 'videographer'"><xsl:value-of select="'vdg'"/></xsl:when>
            <xsl:when test="$role = 'vocalist'"><xsl:value-of select="'voc'"/></xsl:when>
            <xsl:when test="$role = 'writer_of_added_commentary'"><xsl:value-of select="'wac'"/></xsl:when>
            <xsl:when test="$role = 'writer_of_added_lyrics'"><xsl:value-of select="'wal'"/></xsl:when>
            <xsl:when test="$role = 'writer_of_accompanying_material'"><xsl:value-of select="'wam'"/></xsl:when>
            <xsl:when test="$role = 'writer_of_added_text'"><xsl:value-of select="'wat'"/></xsl:when>
            <xsl:when test="$role = 'woodcutter'"><xsl:value-of select="'wdc'"/></xsl:when>
            <xsl:when test="$role = 'wood_engraver'"><xsl:value-of select="'wde'"/></xsl:when>
            <xsl:when test="$role = 'writer_of_introduction'"><xsl:value-of select="'win'"/></xsl:when>
            <xsl:when test="$role = 'witness'"><xsl:value-of select="'wit'"/></xsl:when>
            <xsl:when test="$role = 'writer_of_preface'"><xsl:value-of select="'wpr'"/></xsl:when>
            <xsl:when test="$role = 'writer_of_supplementary_textual_content'"><xsl:value-of select="'wst'"/></xsl:when>
            <xsl:otherwise><xsl:value-of select="'oth'"/></xsl:otherwise>
        </xsl:choose>
    </xsl:function>
    
    <xsl:function name="nlb:marcrel-to-role" as="xs:string">
        <xsl:param name="marcrel" as="xs:string"/>
        <xsl:choose>
            <xsl:when test="$marcrel = 'abr'"><xsl:value-of select="'abridger'"/></xsl:when>
            <xsl:when test="$marcrel = 'acp'"><xsl:value-of select="'art_copyist'"/></xsl:when>
            <xsl:when test="$marcrel = 'act'"><xsl:value-of select="'actor'"/></xsl:when>
            <xsl:when test="$marcrel = 'adi'"><xsl:value-of select="'art_director'"/></xsl:when>
            <xsl:when test="$marcrel = 'adp'"><xsl:value-of select="'adapter'"/></xsl:when>
            <xsl:when test="$marcrel = 'aft'"><xsl:value-of select="'author_of_afterword_or_colophon'"/></xsl:when>
            <xsl:when test="$marcrel = 'anl'"><xsl:value-of select="'analyst'"/></xsl:when>
            <xsl:when test="$marcrel = 'anm'"><xsl:value-of select="'animator'"/></xsl:when>
            <xsl:when test="$marcrel = 'ann'"><xsl:value-of select="'annotator'"/></xsl:when>
            <xsl:when test="$marcrel = 'ant'"><xsl:value-of select="'bibliographic_antecedent'"/></xsl:when>
            <xsl:when test="$marcrel = 'ape'"><xsl:value-of select="'appellee'"/></xsl:when>
            <xsl:when test="$marcrel = 'apl'"><xsl:value-of select="'appellant'"/></xsl:when>
            <xsl:when test="$marcrel = 'app'"><xsl:value-of select="'applicant'"/></xsl:when>
            <xsl:when test="$marcrel = 'aqt'"><xsl:value-of select="'author_in_quotations_or_text_abstracts'"/></xsl:when>
            <xsl:when test="$marcrel = 'arc'"><xsl:value-of select="'architect'"/></xsl:when>
            <xsl:when test="$marcrel = 'ard'"><xsl:value-of select="'artistic_director'"/></xsl:when>
            <xsl:when test="$marcrel = 'arr'"><xsl:value-of select="'arranger'"/></xsl:when>
            <xsl:when test="$marcrel = 'art'"><xsl:value-of select="'artist'"/></xsl:when>
            <xsl:when test="$marcrel = 'asg'"><xsl:value-of select="'assignee'"/></xsl:when>
            <xsl:when test="$marcrel = 'asn'"><xsl:value-of select="'associated_name'"/></xsl:when>
            <xsl:when test="$marcrel = 'ato'"><xsl:value-of select="'autographer'"/></xsl:when>
            <xsl:when test="$marcrel = 'att'"><xsl:value-of select="'attributed_name'"/></xsl:when>
            <xsl:when test="$marcrel = 'auc'"><xsl:value-of select="'auctioneer'"/></xsl:when>
            <xsl:when test="$marcrel = 'aud'"><xsl:value-of select="'author_of_dialog'"/></xsl:when>
            <xsl:when test="$marcrel = 'aui'"><xsl:value-of select="'author_of_introduction'"/></xsl:when>
            <xsl:when test="$marcrel = 'aus'"><xsl:value-of select="'screenwriter'"/></xsl:when>
            <xsl:when test="$marcrel = 'aut'"><xsl:value-of select="'author'"/></xsl:when>
            <xsl:when test="$marcrel = 'bdd'"><xsl:value-of select="'binding_designer'"/></xsl:when>
            <xsl:when test="$marcrel = 'bjd'"><xsl:value-of select="'bookjacket_designer'"/></xsl:when>
            <xsl:when test="$marcrel = 'bkd'"><xsl:value-of select="'book_designer'"/></xsl:when>
            <xsl:when test="$marcrel = 'bkp'"><xsl:value-of select="'book_producer'"/></xsl:when>
            <xsl:when test="$marcrel = 'blw'"><xsl:value-of select="'blurb_writer'"/></xsl:when>
            <xsl:when test="$marcrel = 'bnd'"><xsl:value-of select="'binder'"/></xsl:when>
            <xsl:when test="$marcrel = 'bpd'"><xsl:value-of select="'bookplate_designer'"/></xsl:when>
            <xsl:when test="$marcrel = 'brd'"><xsl:value-of select="'broadcaster'"/></xsl:when>
            <xsl:when test="$marcrel = 'brl'"><xsl:value-of select="'braille_embosser'"/></xsl:when>
            <xsl:when test="$marcrel = 'bsl'"><xsl:value-of select="'bookseller'"/></xsl:when>
            <xsl:when test="$marcrel = 'cas'"><xsl:value-of select="'caster'"/></xsl:when>
            <xsl:when test="$marcrel = 'ccp'"><xsl:value-of select="'conceptor'"/></xsl:when>
            <xsl:when test="$marcrel = 'chr'"><xsl:value-of select="'choreographer'"/></xsl:when>
            <xsl:when test="$marcrel = 'clb'"><xsl:value-of select="'collaborator'"/></xsl:when>
            <xsl:when test="$marcrel = 'cli'"><xsl:value-of select="'client'"/></xsl:when>
            <xsl:when test="$marcrel = 'cll'"><xsl:value-of select="'calligrapher'"/></xsl:when>
            <xsl:when test="$marcrel = 'clr'"><xsl:value-of select="'colorist'"/></xsl:when>
            <xsl:when test="$marcrel = 'clt'"><xsl:value-of select="'collotyper'"/></xsl:when>
            <xsl:when test="$marcrel = 'cmm'"><xsl:value-of select="'commentator'"/></xsl:when>
            <xsl:when test="$marcrel = 'cmp'"><xsl:value-of select="'composer'"/></xsl:when>
            <xsl:when test="$marcrel = 'cmt'"><xsl:value-of select="'compositor'"/></xsl:when>
            <xsl:when test="$marcrel = 'cnd'"><xsl:value-of select="'conductor'"/></xsl:when>
            <xsl:when test="$marcrel = 'cng'"><xsl:value-of select="'cinematographer'"/></xsl:when>
            <xsl:when test="$marcrel = 'cns'"><xsl:value-of select="'censor'"/></xsl:when>
            <xsl:when test="$marcrel = 'coe'"><xsl:value-of select="'contestant_appellee'"/></xsl:when>
            <xsl:when test="$marcrel = 'col'"><xsl:value-of select="'collector'"/></xsl:when>
            <xsl:when test="$marcrel = 'com'"><xsl:value-of select="'compiler'"/></xsl:when>
            <xsl:when test="$marcrel = 'con'"><xsl:value-of select="'conservator'"/></xsl:when>
            <xsl:when test="$marcrel = 'cor'"><xsl:value-of select="'collection_registrar'"/></xsl:when>
            <xsl:when test="$marcrel = 'cos'"><xsl:value-of select="'contestant'"/></xsl:when>
            <xsl:when test="$marcrel = 'cot'"><xsl:value-of select="'contestant_appellant'"/></xsl:when>
            <xsl:when test="$marcrel = 'cou'"><xsl:value-of select="'court_governed'"/></xsl:when>
            <xsl:when test="$marcrel = 'cov'"><xsl:value-of select="'cover_designer'"/></xsl:when>
            <xsl:when test="$marcrel = 'cpc'"><xsl:value-of select="'copyright_claimant'"/></xsl:when>
            <xsl:when test="$marcrel = 'cpe'"><xsl:value-of select="'complainant_appellee'"/></xsl:when>
            <xsl:when test="$marcrel = 'cph'"><xsl:value-of select="'copyright_holder'"/></xsl:when>
            <xsl:when test="$marcrel = 'cpl'"><xsl:value-of select="'complainant'"/></xsl:when>
            <xsl:when test="$marcrel = 'cpt'"><xsl:value-of select="'complainant_appellant'"/></xsl:when>
            <xsl:when test="$marcrel = 'cre'"><xsl:value-of select="'creator'"/></xsl:when>
            <xsl:when test="$marcrel = 'crp'"><xsl:value-of select="'correspondent'"/></xsl:when>
            <xsl:when test="$marcrel = 'crr'"><xsl:value-of select="'corrector'"/></xsl:when>
            <xsl:when test="$marcrel = 'crt'"><xsl:value-of select="'court_reporter'"/></xsl:when>
            <xsl:when test="$marcrel = 'csl'"><xsl:value-of select="'consultant'"/></xsl:when>
            <xsl:when test="$marcrel = 'csp'"><xsl:value-of select="'consultant_to_a_project'"/></xsl:when>
            <xsl:when test="$marcrel = 'cst'"><xsl:value-of select="'costume_designer'"/></xsl:when>
            <xsl:when test="$marcrel = 'ctb'"><xsl:value-of select="'contributor'"/></xsl:when>
            <xsl:when test="$marcrel = 'cte'"><xsl:value-of select="'contestee_appellee'"/></xsl:when>
            <xsl:when test="$marcrel = 'ctg'"><xsl:value-of select="'cartographer'"/></xsl:when>
            <xsl:when test="$marcrel = 'ctr'"><xsl:value-of select="'contractor'"/></xsl:when>
            <xsl:when test="$marcrel = 'cts'"><xsl:value-of select="'contestee'"/></xsl:when>
            <xsl:when test="$marcrel = 'ctt'"><xsl:value-of select="'contestee_appellant'"/></xsl:when>
            <xsl:when test="$marcrel = 'cur'"><xsl:value-of select="'curator'"/></xsl:when>
            <xsl:when test="$marcrel = 'cwt'"><xsl:value-of select="'commentator_for_written_text'"/></xsl:when>
            <xsl:when test="$marcrel = 'dbp'"><xsl:value-of select="'distribution_place'"/></xsl:when>
            <xsl:when test="$marcrel = 'dfd'"><xsl:value-of select="'defendant'"/></xsl:when>
            <xsl:when test="$marcrel = 'dfe'"><xsl:value-of select="'defendant_appellee'"/></xsl:when>
            <xsl:when test="$marcrel = 'dft'"><xsl:value-of select="'defendant_appellant'"/></xsl:when>
            <xsl:when test="$marcrel = 'dgg'"><xsl:value-of select="'degree_granting_institution'"/></xsl:when>
            <xsl:when test="$marcrel = 'dgs'"><xsl:value-of select="'degree_supervisor'"/></xsl:when>
            <xsl:when test="$marcrel = 'dis'"><xsl:value-of select="'dissertant'"/></xsl:when>
            <xsl:when test="$marcrel = 'dln'"><xsl:value-of select="'delineator'"/></xsl:when>
            <xsl:when test="$marcrel = 'dnc'"><xsl:value-of select="'dancer'"/></xsl:when>
            <xsl:when test="$marcrel = 'dnr'"><xsl:value-of select="'donor'"/></xsl:when>
            <xsl:when test="$marcrel = 'dpc'"><xsl:value-of select="'depicted'"/></xsl:when>
            <xsl:when test="$marcrel = 'dpt'"><xsl:value-of select="'depositor'"/></xsl:when>
            <xsl:when test="$marcrel = 'drm'"><xsl:value-of select="'draftsman'"/></xsl:when>
            <xsl:when test="$marcrel = 'drt'"><xsl:value-of select="'director'"/></xsl:when>
            <xsl:when test="$marcrel = 'dsr'"><xsl:value-of select="'designer'"/></xsl:when>
            <xsl:when test="$marcrel = 'dst'"><xsl:value-of select="'distributor'"/></xsl:when>
            <xsl:when test="$marcrel = 'dtc'"><xsl:value-of select="'data_contributor'"/></xsl:when>
            <xsl:when test="$marcrel = 'dte'"><xsl:value-of select="'dedicatee'"/></xsl:when>
            <xsl:when test="$marcrel = 'dtm'"><xsl:value-of select="'data_manager'"/></xsl:when>
            <xsl:when test="$marcrel = 'dto'"><xsl:value-of select="'dedicator'"/></xsl:when>
            <xsl:when test="$marcrel = 'dub'"><xsl:value-of select="'dubious_author'"/></xsl:when>
            <xsl:when test="$marcrel = 'edc'"><xsl:value-of select="'editor_of_compilation'"/></xsl:when>
            <xsl:when test="$marcrel = 'edm'"><xsl:value-of select="'editor_of_moving_image_work'"/></xsl:when>
            <xsl:when test="$marcrel = 'edt'"><xsl:value-of select="'editor'"/></xsl:when>
            <xsl:when test="$marcrel = 'egr'"><xsl:value-of select="'engraver'"/></xsl:when>
            <xsl:when test="$marcrel = 'elg'"><xsl:value-of select="'electrician'"/></xsl:when>
            <xsl:when test="$marcrel = 'elt'"><xsl:value-of select="'electrotyper'"/></xsl:when>
            <xsl:when test="$marcrel = 'eng'"><xsl:value-of select="'engineer'"/></xsl:when>
            <xsl:when test="$marcrel = 'enj'"><xsl:value-of select="'enacting_jurisdiction'"/></xsl:when>
            <xsl:when test="$marcrel = 'etr'"><xsl:value-of select="'etcher'"/></xsl:when>
            <xsl:when test="$marcrel = 'evp'"><xsl:value-of select="'event_place'"/></xsl:when>
            <xsl:when test="$marcrel = 'exp'"><xsl:value-of select="'expert'"/></xsl:when>
            <xsl:when test="$marcrel = 'fac'"><xsl:value-of select="'facsimilist'"/></xsl:when>
            <xsl:when test="$marcrel = 'fds'"><xsl:value-of select="'film_distributor'"/></xsl:when>
            <xsl:when test="$marcrel = 'fld'"><xsl:value-of select="'field_director'"/></xsl:when>
            <xsl:when test="$marcrel = 'flm'"><xsl:value-of select="'film_editor'"/></xsl:when>
            <xsl:when test="$marcrel = 'fmd'"><xsl:value-of select="'film_director'"/></xsl:when>
            <xsl:when test="$marcrel = 'fmk'"><xsl:value-of select="'filmmaker'"/></xsl:when>
            <xsl:when test="$marcrel = 'fmo'"><xsl:value-of select="'former_owner'"/></xsl:when>
            <xsl:when test="$marcrel = 'fmp'"><xsl:value-of select="'film_producer'"/></xsl:when>
            <xsl:when test="$marcrel = 'fnd'"><xsl:value-of select="'funder'"/></xsl:when>
            <xsl:when test="$marcrel = 'fpy'"><xsl:value-of select="'first_party'"/></xsl:when>
            <xsl:when test="$marcrel = 'frg'"><xsl:value-of select="'forger'"/></xsl:when>
            <xsl:when test="$marcrel = 'gis'"><xsl:value-of select="'geographic_information_specialist'"/></xsl:when>
            <xsl:when test="$marcrel = 'grt'"><xsl:value-of select="'graphic_technician'"/></xsl:when>
            <xsl:when test="$marcrel = 'his'"><xsl:value-of select="'host_institution'"/></xsl:when>
            <xsl:when test="$marcrel = 'hnr'"><xsl:value-of select="'honoree'"/></xsl:when>
            <xsl:when test="$marcrel = 'hst'"><xsl:value-of select="'host'"/></xsl:when>
            <xsl:when test="$marcrel = 'ill'"><xsl:value-of select="'illustrator'"/></xsl:when>
            <xsl:when test="$marcrel = 'ilu'"><xsl:value-of select="'illuminator'"/></xsl:when>
            <xsl:when test="$marcrel = 'ins'"><xsl:value-of select="'inscriber'"/></xsl:when>
            <xsl:when test="$marcrel = 'inv'"><xsl:value-of select="'inventor'"/></xsl:when>
            <xsl:when test="$marcrel = 'isb'"><xsl:value-of select="'issuing_body'"/></xsl:when>
            <xsl:when test="$marcrel = 'itr'"><xsl:value-of select="'instrumentalist'"/></xsl:when>
            <xsl:when test="$marcrel = 'ive'"><xsl:value-of select="'interviewee'"/></xsl:when>
            <xsl:when test="$marcrel = 'ivr'"><xsl:value-of select="'interviewer'"/></xsl:when>
            <xsl:when test="$marcrel = 'jud'"><xsl:value-of select="'judge'"/></xsl:when>
            <xsl:when test="$marcrel = 'jug'"><xsl:value-of select="'jurisdiction_governed'"/></xsl:when>
            <xsl:when test="$marcrel = 'lbr'"><xsl:value-of select="'laboratory'"/></xsl:when>
            <xsl:when test="$marcrel = 'lbt'"><xsl:value-of select="'librettist'"/></xsl:when>
            <xsl:when test="$marcrel = 'ldr'"><xsl:value-of select="'laboratory_director'"/></xsl:when>
            <xsl:when test="$marcrel = 'led'"><xsl:value-of select="'lead'"/></xsl:when>
            <xsl:when test="$marcrel = 'lee'"><xsl:value-of select="'libelee_appellee'"/></xsl:when>
            <xsl:when test="$marcrel = 'lel'"><xsl:value-of select="'libelee'"/></xsl:when>
            <xsl:when test="$marcrel = 'len'"><xsl:value-of select="'lender'"/></xsl:when>
            <xsl:when test="$marcrel = 'let'"><xsl:value-of select="'libelee_appellant'"/></xsl:when>
            <xsl:when test="$marcrel = 'lgd'"><xsl:value-of select="'lighting_designer'"/></xsl:when>
            <xsl:when test="$marcrel = 'lie'"><xsl:value-of select="'libelant_appellee'"/></xsl:when>
            <xsl:when test="$marcrel = 'lil'"><xsl:value-of select="'libelant'"/></xsl:when>
            <xsl:when test="$marcrel = 'lit'"><xsl:value-of select="'libelant_appellant'"/></xsl:when>
            <xsl:when test="$marcrel = 'lsa'"><xsl:value-of select="'landscape_architect'"/></xsl:when>
            <xsl:when test="$marcrel = 'lse'"><xsl:value-of select="'licensee'"/></xsl:when>
            <xsl:when test="$marcrel = 'lso'"><xsl:value-of select="'licensor'"/></xsl:when>
            <xsl:when test="$marcrel = 'ltg'"><xsl:value-of select="'lithographer'"/></xsl:when>
            <xsl:when test="$marcrel = 'lyr'"><xsl:value-of select="'lyricist'"/></xsl:when>
            <xsl:when test="$marcrel = 'mcp'"><xsl:value-of select="'music_copyist'"/></xsl:when>
            <xsl:when test="$marcrel = 'mdc'"><xsl:value-of select="'metadata_contact'"/></xsl:when>
            <xsl:when test="$marcrel = 'med'"><xsl:value-of select="'medium'"/></xsl:when>
            <xsl:when test="$marcrel = 'mfp'"><xsl:value-of select="'manufacture_place'"/></xsl:when>
            <xsl:when test="$marcrel = 'mfr'"><xsl:value-of select="'manufacturer'"/></xsl:when>
            <xsl:when test="$marcrel = 'mod'"><xsl:value-of select="'moderator'"/></xsl:when>
            <xsl:when test="$marcrel = 'mon'"><xsl:value-of select="'monitor'"/></xsl:when>
            <xsl:when test="$marcrel = 'mrb'"><xsl:value-of select="'marbler'"/></xsl:when>
            <xsl:when test="$marcrel = 'mrk'"><xsl:value-of select="'markup_editor'"/></xsl:when>
            <xsl:when test="$marcrel = 'msd'"><xsl:value-of select="'musical_director'"/></xsl:when>
            <xsl:when test="$marcrel = 'mte'"><xsl:value-of select="'metal_engraver'"/></xsl:when>
            <xsl:when test="$marcrel = 'mtk'"><xsl:value-of select="'minute_taker'"/></xsl:when>
            <xsl:when test="$marcrel = 'mus'"><xsl:value-of select="'musician'"/></xsl:when>
            <xsl:when test="$marcrel = 'nrt'"><xsl:value-of select="'narrator'"/></xsl:when>
            <xsl:when test="$marcrel = 'opn'"><xsl:value-of select="'opponent'"/></xsl:when>
            <xsl:when test="$marcrel = 'org'"><xsl:value-of select="'originator'"/></xsl:when>
            <xsl:when test="$marcrel = 'orm'"><xsl:value-of select="'organizer'"/></xsl:when>
            <xsl:when test="$marcrel = 'osp'"><xsl:value-of select="'onscreen_presenter'"/></xsl:when>
            <xsl:when test="$marcrel = 'own'"><xsl:value-of select="'owner'"/></xsl:when>
            <xsl:when test="$marcrel = 'pan'"><xsl:value-of select="'panelist'"/></xsl:when>
            <xsl:when test="$marcrel = 'pat'"><xsl:value-of select="'patron'"/></xsl:when>
            <xsl:when test="$marcrel = 'pbd'"><xsl:value-of select="'publishing_director'"/></xsl:when>
            <xsl:when test="$marcrel = 'pbl'"><xsl:value-of select="'publisher'"/></xsl:when>
            <xsl:when test="$marcrel = 'pdr'"><xsl:value-of select="'project_director'"/></xsl:when>
            <xsl:when test="$marcrel = 'pfr'"><xsl:value-of select="'proofreader'"/></xsl:when>
            <xsl:when test="$marcrel = 'pht'"><xsl:value-of select="'photographer'"/></xsl:when>
            <xsl:when test="$marcrel = 'plt'"><xsl:value-of select="'platemaker'"/></xsl:when>
            <xsl:when test="$marcrel = 'pma'"><xsl:value-of select="'permitting_agency'"/></xsl:when>
            <xsl:when test="$marcrel = 'pmn'"><xsl:value-of select="'production_manager'"/></xsl:when>
            <xsl:when test="$marcrel = 'pop'"><xsl:value-of select="'printer_of_plates'"/></xsl:when>
            <xsl:when test="$marcrel = 'ppm'"><xsl:value-of select="'papermaker'"/></xsl:when>
            <xsl:when test="$marcrel = 'ppt'"><xsl:value-of select="'puppeteer'"/></xsl:when>
            <xsl:when test="$marcrel = 'pra'"><xsl:value-of select="'praeses'"/></xsl:when>
            <xsl:when test="$marcrel = 'prc'"><xsl:value-of select="'process_contact'"/></xsl:when>
            <xsl:when test="$marcrel = 'prd'"><xsl:value-of select="'production_personnel'"/></xsl:when>
            <xsl:when test="$marcrel = 'pre'"><xsl:value-of select="'presenter'"/></xsl:when>
            <xsl:when test="$marcrel = 'prf'"><xsl:value-of select="'performer'"/></xsl:when>
            <xsl:when test="$marcrel = 'prg'"><xsl:value-of select="'programmer'"/></xsl:when>
            <xsl:when test="$marcrel = 'prm'"><xsl:value-of select="'printmaker'"/></xsl:when>
            <xsl:when test="$marcrel = 'prn'"><xsl:value-of select="'production_company'"/></xsl:when>
            <xsl:when test="$marcrel = 'pro'"><xsl:value-of select="'producer'"/></xsl:when>
            <xsl:when test="$marcrel = 'prp'"><xsl:value-of select="'production_place'"/></xsl:when>
            <xsl:when test="$marcrel = 'prs'"><xsl:value-of select="'production_designer'"/></xsl:when>
            <xsl:when test="$marcrel = 'prt'"><xsl:value-of select="'printer'"/></xsl:when>
            <xsl:when test="$marcrel = 'prv'"><xsl:value-of select="'provider'"/></xsl:when>
            <xsl:when test="$marcrel = 'pta'"><xsl:value-of select="'patent_applicant'"/></xsl:when>
            <xsl:when test="$marcrel = 'pte'"><xsl:value-of select="'plaintiff_appellee'"/></xsl:when>
            <xsl:when test="$marcrel = 'ptf'"><xsl:value-of select="'plaintiff'"/></xsl:when>
            <xsl:when test="$marcrel = 'pth'"><xsl:value-of select="'patent_holder'"/></xsl:when>
            <xsl:when test="$marcrel = 'ptt'"><xsl:value-of select="'plaintiff_appellant'"/></xsl:when>
            <xsl:when test="$marcrel = 'pup'"><xsl:value-of select="'publication_place'"/></xsl:when>
            <xsl:when test="$marcrel = 'rbr'"><xsl:value-of select="'rubricator'"/></xsl:when>
            <xsl:when test="$marcrel = 'rcd'"><xsl:value-of select="'recordist'"/></xsl:when>
            <xsl:when test="$marcrel = 'rce'"><xsl:value-of select="'recording_engineer'"/></xsl:when>
            <xsl:when test="$marcrel = 'rcp'"><xsl:value-of select="'addressee'"/></xsl:when>
            <xsl:when test="$marcrel = 'rdd'"><xsl:value-of select="'radio_director'"/></xsl:when>
            <xsl:when test="$marcrel = 'red'"><xsl:value-of select="'redaktor'"/></xsl:when>
            <xsl:when test="$marcrel = 'ren'"><xsl:value-of select="'renderer'"/></xsl:when>
            <xsl:when test="$marcrel = 'res'"><xsl:value-of select="'researcher'"/></xsl:when>
            <xsl:when test="$marcrel = 'rev'"><xsl:value-of select="'reviewer'"/></xsl:when>
            <xsl:when test="$marcrel = 'rpc'"><xsl:value-of select="'radio_producer'"/></xsl:when>
            <xsl:when test="$marcrel = 'rps'"><xsl:value-of select="'repository'"/></xsl:when>
            <xsl:when test="$marcrel = 'rpt'"><xsl:value-of select="'reporter'"/></xsl:when>
            <xsl:when test="$marcrel = 'rpy'"><xsl:value-of select="'responsible_party'"/></xsl:when>
            <xsl:when test="$marcrel = 'rse'"><xsl:value-of select="'respondent_appellee'"/></xsl:when>
            <xsl:when test="$marcrel = 'rsg'"><xsl:value-of select="'restager'"/></xsl:when>
            <xsl:when test="$marcrel = 'rsp'"><xsl:value-of select="'respondent'"/></xsl:when>
            <xsl:when test="$marcrel = 'rsr'"><xsl:value-of select="'restorationist'"/></xsl:when>
            <xsl:when test="$marcrel = 'rst'"><xsl:value-of select="'respondent_appellant'"/></xsl:when>
            <xsl:when test="$marcrel = 'rth'"><xsl:value-of select="'research_team_head'"/></xsl:when>
            <xsl:when test="$marcrel = 'rtm'"><xsl:value-of select="'research_team_member'"/></xsl:when>
            <xsl:when test="$marcrel = 'sad'"><xsl:value-of select="'scientific_advisor'"/></xsl:when>
            <xsl:when test="$marcrel = 'sce'"><xsl:value-of select="'scenarist'"/></xsl:when>
            <xsl:when test="$marcrel = 'scl'"><xsl:value-of select="'sculptor'"/></xsl:when>
            <xsl:when test="$marcrel = 'scr'"><xsl:value-of select="'scribe'"/></xsl:when>
            <xsl:when test="$marcrel = 'sds'"><xsl:value-of select="'sound_designer'"/></xsl:when>
            <xsl:when test="$marcrel = 'sec'"><xsl:value-of select="'secretary'"/></xsl:when>
            <xsl:when test="$marcrel = 'sgd'"><xsl:value-of select="'stage_director'"/></xsl:when>
            <xsl:when test="$marcrel = 'sgn'"><xsl:value-of select="'signer'"/></xsl:when>
            <xsl:when test="$marcrel = 'sht'"><xsl:value-of select="'supporting_host'"/></xsl:when>
            <xsl:when test="$marcrel = 'sll'"><xsl:value-of select="'seller'"/></xsl:when>
            <xsl:when test="$marcrel = 'sng'"><xsl:value-of select="'singer'"/></xsl:when>
            <xsl:when test="$marcrel = 'spk'"><xsl:value-of select="'speaker'"/></xsl:when>
            <xsl:when test="$marcrel = 'spn'"><xsl:value-of select="'sponsor'"/></xsl:when>
            <xsl:when test="$marcrel = 'spy'"><xsl:value-of select="'second_party'"/></xsl:when>
            <xsl:when test="$marcrel = 'srv'"><xsl:value-of select="'surveyor'"/></xsl:when>
            <xsl:when test="$marcrel = 'std'"><xsl:value-of select="'set_designer'"/></xsl:when>
            <xsl:when test="$marcrel = 'stg'"><xsl:value-of select="'setting'"/></xsl:when>
            <xsl:when test="$marcrel = 'stl'"><xsl:value-of select="'storyteller'"/></xsl:when>
            <xsl:when test="$marcrel = 'stm'"><xsl:value-of select="'stage_manager'"/></xsl:when>
            <xsl:when test="$marcrel = 'stn'"><xsl:value-of select="'standards_body'"/></xsl:when>
            <xsl:when test="$marcrel = 'str'"><xsl:value-of select="'stereotyper'"/></xsl:when>
            <xsl:when test="$marcrel = 'tcd'"><xsl:value-of select="'technical_director'"/></xsl:when>
            <xsl:when test="$marcrel = 'tch'"><xsl:value-of select="'teacher'"/></xsl:when>
            <xsl:when test="$marcrel = 'ths'"><xsl:value-of select="'thesis_advisor'"/></xsl:when>
            <xsl:when test="$marcrel = 'tld'"><xsl:value-of select="'television_director'"/></xsl:when>
            <xsl:when test="$marcrel = 'tlp'"><xsl:value-of select="'television_producer'"/></xsl:when>
            <xsl:when test="$marcrel = 'trc'"><xsl:value-of select="'transcriber'"/></xsl:when>
            <xsl:when test="$marcrel = 'trl'"><xsl:value-of select="'translator'"/></xsl:when>
            <xsl:when test="$marcrel = 'tyd'"><xsl:value-of select="'type_designer'"/></xsl:when>
            <xsl:when test="$marcrel = 'tyg'"><xsl:value-of select="'typographer'"/></xsl:when>
            <xsl:when test="$marcrel = 'uvp'"><xsl:value-of select="'university_place'"/></xsl:when>
            <xsl:when test="$marcrel = 'vac'"><xsl:value-of select="'voice_actor'"/></xsl:when>
            <xsl:when test="$marcrel = 'vdg'"><xsl:value-of select="'videographer'"/></xsl:when>
            <xsl:when test="$marcrel = 'voc'"><xsl:value-of select="'vocalist'"/></xsl:when>
            <xsl:when test="$marcrel = 'wac'"><xsl:value-of select="'writer_of_added_commentary'"/></xsl:when>
            <xsl:when test="$marcrel = 'wal'"><xsl:value-of select="'writer_of_added_lyrics'"/></xsl:when>
            <xsl:when test="$marcrel = 'wam'"><xsl:value-of select="'writer_of_accompanying_material'"/></xsl:when>
            <xsl:when test="$marcrel = 'wat'"><xsl:value-of select="'writer_of_added_text'"/></xsl:when>
            <xsl:when test="$marcrel = 'wdc'"><xsl:value-of select="'woodcutter'"/></xsl:when>
            <xsl:when test="$marcrel = 'wde'"><xsl:value-of select="'wood_engraver'"/></xsl:when>
            <xsl:when test="$marcrel = 'win'"><xsl:value-of select="'writer_of_introduction'"/></xsl:when>
            <xsl:when test="$marcrel = 'wit'"><xsl:value-of select="'witness'"/></xsl:when>
            <xsl:when test="$marcrel = 'wpr'"><xsl:value-of select="'writer_of_preface'"/></xsl:when>
            <xsl:when test="$marcrel = 'wst'"><xsl:value-of select="'writer_of_supplementary_textual_content'"/></xsl:when>
            <xsl:otherwise><xsl:value-of select="'other'"/></xsl:otherwise>
        </xsl:choose>
    </xsl:function>
    
</xsl:stylesheet>