<?xml version="1.0" encoding="UTF-8"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform"
                xmlns:xs="http://www.w3.org/2001/XMLSchema"
                xmlns:dc="http://purl.org/dc/elements/1.1/"
                xmlns:SRU="http://www.loc.gov/zing/sru/"
                xmlns:normarc="info:lc/xmlns/marcxchange-v1"
                xmlns:DIAG="http://www.loc.gov/zing/sru/diagnostics/"
                xmlns:rdf="http://www.w3.org/1999/02/22-rdf-syntax-ns#"
                xmlns:schema="http://schema.org/"
                xmlns:frbr="http://purl.org/vocab/frbr/core#"
                xmlns:nlbbib="http://www.nlb.no/bibliographic"
                xmlns:nlb="http://www.nlb.no/"
                xmlns:html="http://www.w3.org/1999/xhtml"
                xmlns:f="#"
                exclude-result-prefixes="#all"
                version="2.0">
    
    <!-- note: assumes input XML is generated by run.py in github.com/nlbdev/bibliofil-dump -->
    
    <xsl:output indent="yes" method="xml"/>
    
    <xsl:template match="@* | node()" mode="#all">
        <xsl:copy exclude-result-prefixes="#all">
            <xsl:apply-templates select="@* | node()" mode="#current"/>
        </xsl:copy>
    </xsl:template>
    
    <xsl:template match="laaner/row | /row">
        <rdf:RDF>
            <xsl:namespace name="nlbbib" select="'http://www.nlb.no/bibliographic'"/>
            <rdf:Description rdf:ID="{@ln_nr}">
                <rdf:type rdf:resource="http://schema.org/Person"/>
                <xsl:for-each select="@*[starts-with(local-name(), 'ln_')]">
                    <xsl:element name="nlbbib:{local-name()}">
                        <xsl:attribute name="rdf:name" select="."/>
                    </xsl:element>
                </xsl:for-each>
                <xsl:for-each select="lnel/row/@*[starts-with(local-name(), 'lnel_')]">
                    <xsl:element name="nlbbib:{local-name()}">
                        <xsl:attribute name="rdf:name" select="."/>
                    </xsl:element>
                </xsl:for-each>
                <xsl:apply-templates select="lmarc/record/*" mode="lmarc"/>
                <xsl:for-each select="res/row">
                    <nlbbib:res>
                        <xsl:for-each select="@*[starts-with(local-name(), 'res_')]">
                            <xsl:element name="nlbbib:{local-name()}">
                                <xsl:attribute name="rdf:name" select="."/>
                            </xsl:element>
                        </xsl:for-each>
                    </nlbbib:res>
                </xsl:for-each>
                <xsl:for-each select="bhist/row">
                    <nlbbib:bhist_tnr rdf:name="{@bhist_tnr}">
                        <nlbbib:bhist_laant rdf:name="{@bhist_laant}"/>
                    </nlbbib:bhist_tnr>
                </xsl:for-each>
            </rdf:Description>
        </rdf:RDF>
    </xsl:template>
    
    <xsl:template match="controlfield | datafield" mode="lmarc">
        <xsl:if test="not((@tag, ../@tag) = ('102','103','150','200','250','260','271','272','273','300','466','467','500','516','517','518','521','600'))">
            <xsl:message select="concat('Ignored ', local-name(), ': ', @tag)"/>
            <!--<xsl:copy exclude-result-prefixes="#all">
                <xsl:apply-templates select="@* | node()" mode="#default"/>
            </xsl:copy>-->
        </xsl:if>
    </xsl:template>
    
    <xsl:template match="controlfield[@tag='001']" mode="lmarc">
        <xsl:call-template name="lmarc">
            <xsl:with-param name="name" select="'nr'"/>
        </xsl:call-template>
    </xsl:template>
    
    <xsl:template match="datafield[@tag='140']" mode="lmarc">
        <xsl:for-each select="subfield">
            <xsl:choose>
                <xsl:when test="@code = 'a'">
                    <xsl:call-template name="lmarc">
                        <xsl:with-param name="name" select="'library'"/>
                    </xsl:call-template>
                </xsl:when>
                <xsl:when test="@code = 'i'">
                    <xsl:variable name="context" select="."/>
                    <xsl:for-each select="tokenize(text(), '\s+')">
                        <xsl:call-template name="lmarc">
                            <xsl:with-param name="name" select="'libraryAccess'"/>
                            <xsl:with-param name="value" select="."/>
                            <xsl:with-param name="context" select="$context"/>
                        </xsl:call-template>
                    </xsl:for-each>
                </xsl:when>
            </xsl:choose>
        </xsl:for-each>
    </xsl:template>
    
    <xsl:template match="datafield[@tag='240']" mode="lmarc">
        <xsl:for-each select="subfield">
            <xsl:choose>
                <xsl:when test="@code = 'a'">
                    <xsl:call-template name="lmarc">
                        <xsl:with-param name="name" select="'tlf'"/>
                    </xsl:call-template>
                </xsl:when>
                <xsl:when test="@code = 'c'">
                    <xsl:call-template name="lmarc">
                        <xsl:with-param name="name" select="'tlf_type'"/>
                    </xsl:call-template>
                </xsl:when>
            </xsl:choose>
        </xsl:for-each>
    </xsl:template>
    
    <xsl:template match="datafield[@tag='261']" mode="lmarc">
        <xsl:for-each select="subfield">
            <xsl:choose>
                <xsl:when test="@code = 'a'">
                    <xsl:call-template name="lmarc">
                        <xsl:with-param name="name" select="'pin'"/>
                    </xsl:call-template>
                </xsl:when>
                <xsl:when test="@code = 'b'">
                    <xsl:call-template name="lmarc">
                        <xsl:with-param name="name" select="'pin_date'"/>
                    </xsl:call-template>
                </xsl:when>
            </xsl:choose>
        </xsl:for-each>
    </xsl:template>
    
    <xsl:template match="datafield[@tag='402']" mode="lmarc">
        <xsl:for-each select="subfield">
            <xsl:choose>
                <xsl:when test="@code = 'a' and text() = 'HER'">
                    <xsl:call-template name="lmarc">
                        <xsl:with-param name="name" select="'test_patron'"/>
                        <xsl:with-param name="value" select="'true'"/>
                    </xsl:call-template>
                </xsl:when>
            </xsl:choose>
        </xsl:for-each>
    </xsl:template>
    
    <xsl:template match="datafield[@tag='465']" mode="lmarc">
        <xsl:for-each select="subfield">
            <xsl:choose>
                <xsl:when test="@code = 'h' and text() = 'P'">
                    <xsl:call-template name="lmarc">
                        <xsl:with-param name="name" select="'braille_patron'"/>
                        <xsl:with-param name="value" select="'true'"/>
                    </xsl:call-template>
                </xsl:when>
            </xsl:choose>
        </xsl:for-each>
    </xsl:template>
    
    <xsl:template match="datafield[@tag='468']" mode="lmarc">
        <xsl:for-each select="subfield">
            <xsl:choose>
                <xsl:when test="@code = 'a'">
                    <xsl:call-template name="lmarc">
                        <xsl:with-param name="name" select="'preferredPlayer'"/>
                    </xsl:call-template>
                </xsl:when>
            </xsl:choose>
        </xsl:for-each>
    </xsl:template>
    
    <xsl:template match="datafield[@tag='469']" mode="lmarc">
        <xsl:variable name="datafield" select="."/>
        
        <xsl:if test="subfield[@code='a']">
            <xsl:variable name="subscription" as="element()">
                <xsl:for-each select="(subfield[@code='a'])[1]">
                    <xsl:call-template name="lmarc">
                        <xsl:with-param name="name" select="'subscription'"/>
                        <xsl:with-param name="value" select="tokenize(text(), '\s+')[1]"/>
                    </xsl:call-template>
                </xsl:for-each>
            </xsl:variable>
            
            <xsl:for-each select="$subscription">
                <xsl:copy exclude-result-prefixes="#all">
                    <xsl:copy-of select="@* | node()" exclude-result-prefixes="#all"/>
                    
                    <xsl:for-each select="$datafield/subfield">
                        <xsl:choose>
                            <xsl:when test="@code = 'd'">
                                <xsl:call-template name="lmarc">
                                    <xsl:with-param name="name" select="'subscriptionStarted'"/>
                                </xsl:call-template>
                            </xsl:when>
                        </xsl:choose>
                    </xsl:for-each>
                </xsl:copy>
            </xsl:for-each>
        </xsl:if>
    </xsl:template>
    
    <xsl:template name="lmarc">
        <xsl:param name="name" as="xs:string"/>
        <xsl:param name="value" select="()" as="xs:string?"/>
        <xsl:param name="context" select="." as="element()"/>
        <xsl:element name="nlbbib:lmarc_{$name}">
            <xsl:attribute name="rdf:name" select="($value, $context/text())[1]"/>
            <xsl:call-template name="lmarc-source">
                <xsl:with-param name="context" select="$context"/>
            </xsl:call-template>
        </xsl:element>
    </xsl:template>
    
    <xsl:template name="lmarc-source">
        <xsl:param name="context" select="." as="element()"/>
        <!--<nlbbib:source rdf:name="{if ($context/self::subfield) then concat($context/../@tag, '$', $context/@code) else $context/@tag}"/>-->
    </xsl:template>
    
</xsl:stylesheet>